### ISSUE TITLE
Aggregation innacuracies

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#1001]
> premature optimization is the root of all evil
>
> -- <cite>Donald E. Knuth</cite>

The spatial aggregation suffers from a numeric problem that affects how points are assigned to clusters in tiles of high zoom levels and far from the origin of coordinates.

The problem, gratuitously introduced by yours truly, is that the expression to compute the aggregation resolution (size of the cells), originally `CDB_XYZ_Resolution(CDB_ZoomFromScale(!scale_denominator!))` (here for resolution 1) was *optimized* as `!scale_denominator!*0.00028`.
In theory that expression makes sense, and by looking at how [mapnik seems to compute it](https://github.com/mapnik/mapnik/blob/b7e486d3c357b533985497ad24c7a003c06a72ee/src/scale_denominator.cpp#L35-L43) it should be accurate.

But for some reason I can't understand yet, the values of `!scale_denominator!` seem to be rounded to 6 significant digits before they are injected in the SQL code.

Now, we compute grid cells for a point x, y as `gx=floor(x/cell_size) gy=floor(y/cell_size)`
to adscribe each point to an aggregation cell (cluster).

An inaccuracy in cell_size will accumulate as we get away from the origin, and when the coordinate values are much greater than the cell_size this will be a problem.

This table shows for Z levels from 1 to 20, and resolution = 1, the *maximum error* (at 180 degrees longitude from the origin or latitude 85) in meters and as percentage of the cell size that occurs when assigning points to cells.
This means that points are "moved" this distance when aggregated (so they can end up in the wrong cell). (remember this is the maximum, error increases linearly from the origin)

|  z | cell size | error m | error % |
|---:|----------:|--------:|--------:|
| 1 | 78272.0 | 9.0 | 0.012 |
| 2 | 39136.0 | 62.0 | 0.16 |
| 3 | 19568.0 | 5.0 | 0.025 |
| 4 | 9784.0 | 24.0 | 0.24 |
| 5 | 4892.0 | 24.0 | 0.49 |
| 6 | 2446.0 | 0.86 | 0.035 |
| 7 | 1223.0 | 0.86 | 0.07 |
| 8 | 611.0 | 45.0 | 7.0 |
| 9 | 306.0 | 45.0 | 15.0 |
| 10 | 153.0 | 8.0 | 5.0 |
| 11 | 76.0 | 28.0 | 37.0 |
| 12 | 38.0 | 45.0 | 118.0 |
| 13 | 19.0 | 14.0 | 72.0 |
| 14 | 10.0 | 16.0 | 164.0 |
| 15 | 5.0 | 43.0 | 901.0 |
| 16 | 2.0 | 4.0 | 164.0 |
| 17 | 1.0 | 4.0 | 327.0 |
| 18 | 0.6 | 4.0 | 655.0 |
| 19 | 0.3 | 90.0 | 30157.0 |
| 20 | 0.15 | 15.0 | 9968.0 |

For resolutions higher than 1 the error increases too, add the logarithm of the resolution to the zoom level to find the corresponding error, e.g. for resolution = 4 use the row for zoom+2.

Note that the expression `CDB_XYZ_Resolution(CDB_ZoomFromScale(!scale_denominator!))` even thoug it uses the rounded scale denominator does not suffer from any imprecision: the zoom level is computed first (which can be determined unambiguosly from the approximate scale since it is a discrete value) and then the resolution for the zoom level is computed accurately. Using this expressions the error are negligible: (extract of the table)

|  z | cell size | error m | error % |
|---:|----------:|--------:|--------:|
| 1 | 78272.0 | 8.3e-10 | 1.1e-12 |
| 2 | 39136.0 | 8.3e-10 | 2.1e-12 |
| 3 | 19568.0 | 8.3e-10 | 4.2e-12 |
| .... |
| 18 | 0.6 | 8.3e-10 | 1.4e-07 |
| 19 | 0.3 | 8.3e-10 | 2.8e-07 |
| 20 | 0.15 | 8.3e-10 | 5.6e-07 |

We also have `!pixel_width!` and `!pixel_height!`. These are more precise than `!scale_denominator!` but still less precise than the `CDB_XYZ_Resolution` expression. For example, here are values for some zoom levels I've measured and the resulting errors (we see error can get big too in extreme cases):

|  z | pixel_width | error m | error % |
|---:|----------:|--------:|--------:|
| 1 | 78272.0 | 4.0 | 0.0055 |
| 5 | 4892.0 | 2.0 | 0.034 |
| 10 | 153.0 | 8.0 | 5.0 |
| 14 | 10.0 | 4.0 | 38.0 |
| 20 | 0.15 | 10.0 | 6928.0 |

I've been writing some tests to detect this problems.
The best solution seems to use `CDB_XYZ_Resolution`.  I have yet to benchmark this solution to see if *optimizations* are required. :grimacing:

While testing this I've detected some troublesome accuracies in `!bbox!` which affects #889

**Comment by Algunenano** [comment]
> But for some reason I can't understand yet, the values of !scale_denominator! seem to be rounded to 6 significant digits before they are injected in the SQL code.

If you are talking about Mapnik, since it's C++ and it's using streams ([`<<`](https://github.com/mapnik/mapnik/blob/b7e486d3c357b533985497ad24c7a003c06a72ee/plugins/input/postgis/postgis_datasource.cpp#L586)) it'll use the [default precision](https://en.cppreference.com/w/cpp/io/ios_base/precision) which is 6 by default.

**Comment by jgoizueta** [comment]
Wow, that would explain it. Thanks @Algunenano

**Comment by Algunenano** [comment]
Funny that we reach this at almost the same time: https://github.com/mapnik/mapnik/pull/3942

Do you we should backport it or we should wait for a 3.1/4 release?
