### ISSUE TITLE
Make sure tests clean up after themselves

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1025]
When running the tests without cleaning up the DBs after (I use this so I can run specific tests by running mocha directly) some redis keys are left behind so tests fail, forcing you to clean redis manually. We should try to have all the tests cleaning their keys to have a nicer environment.

**Comment by oleurud** [comment]
I can't reproduce this issue.

Following your comments, I have commented the `cleanup` function of `run_test.sh` and then, I have run `make test` twice, but all works fine. Am I losing something?

**Comment by Algunenano** [comment]
I don't think so. I've fixed the ones I came up with when doing other PRs and maybe that was enough or other people have done the same and everything is clear now. Thanks!
