### ISSUE TITLE
Aggregation bbox adjustment is not good enough

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#1034]
The adjustment of the bbox (tile + buffer extension) to the aggregation grid we introduced in #1002 still fails for some cases due to the accuracy of the bbox computed by Mapnik.

For example, for tile x=1, y=1, z=2, with buffersize=1, the bbox Mapnik uses is this:
`BOX3D(-39135.7584820101 -39135.7584820101,10057889.92987663 10057889.92987663)`

And the more exact value we compute for the cell size is 39135.7584820102, so the bbox minimum Y is short of 1E-10, which is larger than the relative epsilon we were using for tolerance and the adjusted limits don't include the 1-cell buffer:

```sql
WITH params AS (
  SELECT
    GREATEST(1*CDB_XYZ_Resolution(CDB_ZoomFromScale(1.39771e+08)), 0.00014579206139598132)::double precision AS res,
    ST_SetSRID('BOX3D(-39135.7584820101 -39135.7584820101,10057889.92987663 10057889.92987663)'::box3d, 3857) AS bbox,
    (2*2.220446049250313e-16::double precision) AS eps
)
SELECT
  res,
  st_ymin(bbox) AS ymin, 
  CEIL((ST_YMIN(bbox) - eps*ABS(ST_YMIN(bbox)))/res)*res AS adjusted_ymin
FROM params
```

```
       res        |       ymin        | adjusted_ymin
------------------+-------------------+---------------
 39135.7584820102 | -39135.7584820101 |            -0
(1 row)
```

I think the best way to fix this is to compute our `eps` as a fraction of the cell size, e.g. `1E-10*res`.

This will make sure that we never use a correction larger than the cell size (which could include extra cells in the buffer) and will have the effect of adjusting bbox limits that are closer than that fraction of the cellsize to the nearest cell limit.

So we could do this:

```diff
diff --git a/lib/cartodb/models/aggregation/aggregation-query.js b/lib/cartodb/models/aggregation/aggregation-query.js
index 4ae3bc3..1a3fe5f 100644
--- a/lib/cartodb/models/aggregation/aggregation-query.js
+++ b/lib/cartodb/models/aggregation/aggregation-query.js
@@ -283,16 +283,16 @@ _cdb_res AS (
     SELECT
     ${gridResolution(ctx)} AS res,
     !bbox! AS bbox,
-    (2*2.220446049250313e-16::double precision) AS eps
+    (1E-10::double precision) AS eps
 ),
 _cdb_params AS (
     SELECT
       res,
       bbox,
-      CEIL((ST_XMIN(bbox) - eps*ABS(ST_XMIN(bbox)))/res)*res AS xmin,
-      FLOOR((ST_XMAX(bbox) + eps*ABS(ST_XMAX(bbox)))/res)*res AS xmax,
-      CEIL((ST_YMIN(bbox) - eps*ABS(ST_YMIN(bbox)))/res)*res AS ymin,
-      FLOOR((ST_YMAX(bbox) + eps*ABS(ST_YMAX(bbox)))/res)*res AS ymax
+      CEIL((ST_XMIN(bbox) - eps*res)/res)*res AS xmin,
+      FLOOR((ST_XMAX(bbox) + eps*res)/res)*res AS xmax,
+      CEIL((ST_YMIN(bbox) - eps*res)/res)*res AS ymin,
+      FLOOR((ST_YMAX(bbox) + eps*res)/res)*res AS ymax
       FROM _cdb_res
 )
```

That would fix [this problem](https://github.com/CartoDB/carto-vl/issues/922) in CARTO VL.

**Comment by Algunenano** [comment]
I think this was fully done already
