### ISSUE TITLE
Shut the process down gracefully

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#1065]
As per [Node.js documentation](https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_warning_using_uncaughtexception_correctly) warms, we should implement a graceful shutdown for the service whenever the process has to deal with `uncaughtException` or `unhandledRejection` events or when the process receives OS's signals such as SIGTERM and SIGINT. That means, we need to handle all incoming request before closing the server and liberate all the resources the process may have allocated, then we can exit the process gracefully.

**Comment by dgaubert** [comment]
I wouldn't extract `process.on('SIGHUP', reopenLogFileStreams(clusterProcess, logger));`, as it doesn't have nothing to do with `exitHandlers`. 

On the other hand, I have a mixed feeling trying to extract them to a different module. I prefer to duplicate `exitHandlers` code in Windshaft-cartodb and see how it evolves before creating a new module prematurely.

I want to know what point of view you have?

**Comment by Algunenano** [comment]
This was already implemented right?
