### ISSUE TITLE
Histogram performance improvement

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1074]
In the histogram SQL query, the `__cdb_iqrange` table is declared as a CTE but only used once. A quick  test show a query time reduced from 1.3 s to 1.0 when inlining it instead (obviously this depends on the data)

cc/ @CartoDB/rt-managers

**Comment by javitonino** [comment]
Removing this from RT. This is not urgent. If you feel this is important, let's do a project for it.
