### ISSUE TITLE
Memory leak in node-postgres

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/Windshaft-cartodb#1078]
I've done some **heap** memory profiling over the app in a somewhat heavy instantiation scenario (20 new instantiations per second) and found that we are leaking big strings in node-postgres:
![image](https://user-images.githubusercontent.com/664253/53653324-59e67500-3c4b-11e9-9df1-2f38135387d7.png)

This is better explained in https://github.com/brianc/node-postgres/issues/1417

The impact of this is limited, but worth considering on long runs.

**Comment by dgaubert** [comment]
cc/ @CartoDB/rt-managers

**Comment by Algunenano** [comment]
Closing stale ticket
