### ISSUE TITLE
npm install not working with node 10.x on OS 10.14.3

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/Windshaft-cartodb#1081]
## Problem
`npm install` doesn't work with current master in my macOS, as it throws several errors when installing this package --> `"canvas": "github:cartodb/node-canvas#1.6.2-cdb3"`. 

It looks like a problem with **clang** c++ compiler.

## Environment
sw_vers
> ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

node -v
> 10.15.2

npm -v
> 6.4.1

gcc -v
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

## Detailed errors

There are 4 errors thrown (besides quite a lot of Warnings, omitted here)
```
> canvas@1.6.2-cdb3 install /Users/victor/CARTO/Windshaft-cartodb/node_modules/windshaft/node_modules/canvas
> node-gyp rebuild

[... OMMITED ...]

../src/CanvasRenderingContext2d.cc:1979:7: error: no
      member named 'isnan' in namespace 'std'
  if (isnan(offset) || isinf(offset)) return;
      ^~~~~~~~~~~~~
../src/CanvasRenderingContext2d.cc:29:23: note: expanded
      from macro 'isnan'
#define isnan(x) std::isnan(x)
                 ~~~~~^
../src/CanvasRenderingContext2d.cc:1979:24: error: no
      member named 'isinf' in namespace 'std'
  if (isnan(offset) || isinf(offset)) return;


  ../src/CanvasRenderingContext2d.cc:1945:21: error: no
        member named 'isnan' in namespace 'std'
      if (a[i] < 0 || isnan(a[i]) || isinf(a[i])) return;
                      ^~~~~~~~~~~
  ../src/CanvasRenderingContext2d.cc:29:23: note: expanded
        from macro 'isnan'
  #define isnan(x) std::isnan(x)
                   ~~~~~^
  ../src/CanvasRenderingContext2d.cc:1945:36: error: no
        member named 'isinf' in namespace 'std'
      if (a[i] < 0 || isnan(a[i]) || isinf(a[i])) return;
```

This comes from https://github.com/CartoDB/node-canvas and it looks like this very same problem in the original project upstream: https://github.com/Automattic/node-canvas/issues/1300

They say that it was fixed in 1.6.3 (and it looks like we're using now a fork based on 1.6.2).

In a quite similar issue at https://forums.developer.apple.com/thread/110594 the answer points to "You need to use the <cmath> header for C++, not <math.h>"

**Comment by VictorVelarde** [comment]
## Failed workaround 

I have tried to fix my problem using gcc instead or clang, but without success.

These are the steps I have followed:

Install gcc
```
  brew update
  brew upgrade
  brew info gcc
  brew install gcc
  brew cleanup
```
> Note: Last line removes previous application/dependency revisions saving considerable space

To check the target path, use again `brew info gcc`, which returns:
> gcc: stable 8.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/8.3.0 (1,413 files, 288.6MB)
...[omitted]

To activate the new gcc when using `npm install` in the project I have tried:
```
env CC=/usr/local/Cellar/gcc/8.3.0/bin/gcc-8 CXX=/usr/local/Cellar/gcc/8.3.0/bin/g++-8 npm install
```

But it fails with:
```
> canvas@1.6.2-cdb3 install /Users/victor/CARTO/Windshaft-cartodb/node_modules/windshaft/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
g++-8: error: unrecognized command line option '-stdlib=libc++'
```

So it looks like, even changing to another gcc, I have problems. 

It would be nice to upgrade the fork, at least to 1.6.3, and see if it works nicely for all of us.

**Comment by dgaubert** [comment]
You'll need a newer version of `gcc` & `g++`, you have `C++ 10` installed. In [documentation](https://github.com/CartoDB/Windshaft-cartodb/blob/master/INSTALL.md#requirements) specifies that you need `C++ 11` which it comes with both `gcc` & `g++` 4.9.

**Comment by VictorVelarde** [comment]
Now that Windshaft is running in my vagrant I'm not in a hurry anymore but I've been trying a bit more without success:

```
brew install gcc@4.9
brew info gcc@4.9
```
It returns the installation path, as `/usr/local/Cellar/gcc@4.9/4.9.4_1`

So to install the modules, I have tried with:
`env CC=/usr/local/Cellar/gcc@4.9/4.9.4_1/bin/gcc-4.9 CXX=/usr/local/Cellar/gcc@4.9/4.9.4_1/bin/g++-4.9 npm install`

But it still complains, failing with something like:

```
> windshaft-cartodb@7.1.0 preinstall /Users/victor/CARTO/Windshaft-cartodb
> make pre-install

> canvas@github:cartodb/node-canvas#45bd3c7cc5e6f99ba75b0d417b6ac6384b43083d install /Users/victor/CARTO/Windshaft-cartodb/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
g++-4.9: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/victor/.nvm/versions/node/v10.15.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
```

**Comment by dgaubert** [comment]
cc/ @CartoDB/rt-managers to prioritize it

**Comment by javitonino** [comment]
:wave: 

I'm going to deprioritize this since MacOS is not an officially supported OS anyway. That said, it'd be nice to keep this working.

The GCC error you are seeing is because `stdlib` is a Clang option and GCC does not recognize it. Two options:
- It is a cached configure option (and you should be able to fix it by `rm -rf node_modules` and rebuilding
- `node-canvas` does not support GCC in Mac

@VictorVelarde Can you try removing the node modules and rebuilding with GCC from scratch, in case you didn't do it before? If this doesn't work: You mentioned that this should work with canvas 1.6.3. Can you try building it? Just initializing a node project and add canvas 1.6.3 as a dependency and trying to install it should be enough.

@dgaubert Maybe we can update canvas to 1.6.3 which just includes a compilation fix for clang if this works?

**Comment by VictorVelarde** [comment]
@dgaubert @javitonino I'm ok with giving this less priority... I got here when I had some problems with the vagrant, and now those problems are gone (after using `npm ci`, instead of `npm install` for this project).

Regarding to removing node_modules, I tried it from scratch, but without success. So after testing `clang` and different `gcc` versions, I think we can safely assume that right now MacOS Mojave is not supported by the project.

Having said that, I would like to help with the update, to return `macOS / clang` compatibility back, so I've run the basic test suggested by @javitonino. I've created an empty project to test the library compilation during install (using clang):

<details>
<summary>gcc -v</summary>
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/
Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
</details>

- First test: `npm -i canvas@1.6.2` --> 123 warnings and **4 errors generated**
- Second test: `npm -i canvas@1.6.3` --> 2 warnings (0 errors)

So yes, it seems that 1.6.3 would be enough to keep compatibility with my current clang (v10.0, from Sept-2018).

**Comment by javitonino** [comment]
@dgaubert Maybe just updating this dependency is enough to make MacOS people happy. Maybe we can just update this in master and deploy it with the next release.

**Comment by dgaubert** [comment]
We use a forked version of[ node-canvas](https://github.com/CartoDB/node-canvas/tree/cdb-1.6.x) which is based on version `1.6.2` I will need to update the fork, release a new version and update in Winshaft and then Windshaft-cartodb.

**Comment by dgaubert** [comment]
I went one step further and I've updated `node-canvas` to version `2.4.1` (we've just stopped using our forked version). @VictorVelarde, update your local environment; it should fix your issues while installing `Windshaft-cartodb`. 

Closing, please re-open if needed.

**Comment by VictorVelarde** [comment]
Thx @dgaubert that's great!
