### ISSUE TITLE
Maqpnik - missing (dependency or link) gdal and ogr

### ISSUE THREAD

**Issue by christophekey** [CartoDB/Windshaft-cartodb#1101]
Recent changes in Windshaft appears to have broken Carto on Docker. Having pulled hair when trying to get https up and running using Glarocs branch, falling back to Stefans Docker set up I find that the problem wasn't me trying to proxy NGINX after all (thats good at least)

Error messages arising:

Mapnik LOG> 2019-06-11 13:45:43: Problem loading plugin library: /Windshaft-cartodb/node_modules/@carto/mapnik/lib/binding/lib/mapnik/input/gdal.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)

Mapnik LOG> 2019-06-11 13:45:43: Problem loading plugin library: /Windshaft-cartodb/node_modules/@carto/mapnik/lib/binding/lib/mapnik/input/ogr.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)

so we can see something is missing (dependency or link) or is it?

Going through Yarn and checking

    yarn list
    yarn check
    yarn check -integrity
    yarn check --verify-tree

doesnt yield any helpful clues. docker container logs gives - [2019-06-11T13:46:00.991479 #203] INFO -- : Ignoring statsd, because there were a error loading the config, so time to explore further.

**Comment by dgaubert** [comment]
Please, can you share more details to understand better what's going on?

To help you, we'll need to know:
 - Node.js version
 - npm version
 - Docker image (OS, setup, etc..)

On the other hand, since the last major release [7.0.0](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md#700) we drop support for `yarn` and we removed `yarn.lock` file. Thus, the recommended way to install `Windshaft-cartodb` is through `npm`.

**Comment by occupinyc** [comment]
Did we ever find a fix for this??

**Comment by Algunenano** [comment]
> Did we ever find a fix for this??

Can you confirm if this still happens if you do a clean installation (no node_modules/) with `npm ci`?

Also, make sure you have the dependencies necessary to use the Mapnik prebuilt module:
```
In Linux, the Mapnik prebuilt module requires GLIBCXX_3.4.21 (GCC 5.1.0 / libstdc++-5 or higher). In OSX, the minimum requirement is 10.9. 
```

**Comment by Algunenano** [comment]
Stale
