### ISSUE TITLE
Add testcases for statsd communication

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#157]
A test should emulate statsd server and allow inspecting what's being sent.

**Comment by rochoa** [comment]
There are already some tests in Windshaft:
 - https://github.com/CartoDB/Windshaft/blob/0.45.0/test/unit/stats_client.test.js
 - https://github.com/CartoDB/Windshaft/blob/0.45.0/test/unit/controllers/tile_stats.test.js
