### ISSUE TITLE
Add testcase for Varnish communication

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#158]
Should be enabled during acceptance tests, with VarnishEmu.
Currently is only done in its own, unit-like, test instead.

**Comment by rochoa** [comment]
There are specific tests for surrogate-keys now in https://github.com/CartoDB/Windshaft-cartodb/blob/master/test/acceptance/cache/surrogate_keys_invalidation.js

Previous varnish invalidation is no longer needed so I'm closing this issue.
