### ISSUE TITLE
Allow specifying a map configuration id with tools/show_style

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#187]
You used to be able to pass a "map token" to tools/show_style using tilde syntax (~<token>) but that's not supported anymore since 1.7.0, where detached maps configuration moved from ``map_style|*`` to ``map_cfg|*``.

**Comment by rochoa** [comment]
We are discouraging these tools so closing this.

https://github.com/CartoDB/Windshaft-cartodb/commit/9ea2029f812b5e8ac84762255be43fa89152311a
