### ISSUE TITLE
creating a named map without layergroup attribute does not fail

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#196]
it is created but when you try to instanciate it raises an exception:

the stack:

{"error":"SyntaxError: Unexpected token u","stack":"SyntaxError: Unexpected token u\n    at Object.parse (native)\n    at TemplateMaps.o.instance (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/lib/cartodb/template_maps.js:597:25)\n    at Function.checkAuthorized (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/lib/cartodb/cartodb_windshaft.js:553:31)\n    at next (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/node_modules/step/lib/step.js:51:23)\n    at Function.finish (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/lib/cartodb/template_maps.js:527:7)\n    at next (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/node_modules/step/lib/step.js:51:23)\n    at next (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/node_modules/step/lib/step.js:63:7)\n    at Function.releaseRedisClient (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/lib/cartodb/template_maps.js:93:7)\n    at next (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/node_modules/step/lib/step.js:51:23)\n    at try_callback (/Users/javi/wrk/viz/cartodb/Windshaft-cartodb/node_modules/redis/index.js:579:9)"}

**Comment by rochoa** [comment]
Basic layergroup validation was introduced in https://github.com/CartoDB/Windshaft-cartodb/pull/248
