### ISSUE TITLE
use curl with https

### ISSUE THREAD

**Issue by bodman** [CartoDB/Windshaft-cartodb#212]
using curl with https returns :
curl: (77) error setting certificate verify locations:
  CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none

**Comment by rochoa** [comment]
Did you see this PR https://github.com/CartoDB/Windshaft/pull/221

**Comment by rochoa** [comment]
OK, didn't hear anything about this for a month, sorry but I'm closing it.
