### ISSUE TITLE
PUT, POST and DELTE to named maps should invalidate varnish

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#233]
right now when a named map is updated the instances of the maps are not invalidated

cc @zenitraM

**Comment by rochoa** [comment]
I duplicated this ticket on #247.

Do we want to invalidate on POST?

**Comment by javisantana** [comment]
I think PUT and DELETE are the ones, right?

**Comment by rochoa** [comment]
:-) https://github.com/CartoDB/Windshaft-cartodb/blob/247-add-named-maps-surrogate-keys/lib/cartodb/cartodb_windshaft.js#L72

**Comment by rochoa** [comment]
This was implemented in https://github.com/CartoDB/Windshaft-cartodb/pull/249
