### ISSUE TITLE
named maps should be accepted in mapconfig

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#239]
we realized about this situation: an user having a named map wants to get a preview of that named map + basemap using cartodb.js

Since the user only has the named map they should be able to send the named map in mapconfig so:

```
{
...
layers: [
{
type: 'http',
template: '...',
},
{
type: 'named',
name: 'whatever'
params: { color: 'red', ...} 
}
]
}
```

We should discuss is this makes sense cc @javierarce

**Comment by rochoa** [comment]
My original idea for that case was to make mandatory to specify the basemap in the mapconfig from the very beginning (so you had to sent it when creating the named map) but I understand that's far from ideal for all cases. If you find this other approach more convenient I'm willing to implement it.

**Comment by rochoa** [comment]
I forgot to close this via commit message but this was implemented in version https://github.com/CartoDB/Windshaft-cartodb/releases/tag/1.27.0
