### ISSUE TITLE
millstone seems to be missing from package.json

### ISSUE THREAD

**Issue by rdewaele** [CartoDB/Windshaft-cartodb#241]
Today I tried running the HEAD version and -- of course after running npm install, twice -- I got the following error:

module.js:340
    throw err;
          ^
Error: Cannot find module 'millstone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/surveillance-portal-generation-script/cartodb_installer/cartodb_installation/Windshaft-cartodb/node_modules/windshaft/node_modules/grainstore/lib/grainstore/mml_builder.js:5:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

After I proceeded with npm install millstone@'0.6.14' (the shrinkwrap file did specify a version), windshaft started without hesitation.

Sorry for not including a pull request, but I am rather new at node and npm and I can't be 100% sure about my problem analysis. ;-) Maybe millstone was previously installed as an indirect dependency?

**Comment by rochoa** [comment]
Hi,
Do you mind sharing your Node.js version and your operative system?

thanks in advance

**Comment by rdewaele** [comment]
$ node --version
v0.10.25

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

It also might have been cosmic radiation, because I ran through the installation process on another instance of the same machine and did not encounter this problem. (However, I scripted my installation procedure, so it's unlikely I did something different during the setup.)

I'll make sure to inform you should I run into the same issue once more.

**Comment by rochoa** [comment]
Thanks a lot for the information.

It's a bit weird since [we use travis to run windshaft-cartodb tests](https://travis-ci.org/CartoDB/Windshaft-cartodb) and we don't do anything custom to run them: https://github.com/CartoDB/Windshaft-cartodb/blob/master/.travis.yml

**Comment by rochoa** [comment]
This could happen due a temporal glitch either with npm registry or github raw content. So I'm closing if there is no more information or until we receive more complaints about it :smiley:
