### ISSUE TITLE
Review buffer size settings for raster

### ISSUE THREAD

**Issue by rafatower** [CartoDB/Windshaft-cartodb#251]
There's some performance issues with raster that might be solved by setting `buffer-size` for the raster layer to zero.

See https://github.com/mapnik/mapnik/pull/2615 and https://github.com/mapnik/mapnik/issues/2405

**Comment by dgaubert** [comment]
We released [MapConfig 1.6.0](https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.6.0.md) which brings the ability to harmonize the `buffer size` for each format:
```
buffersize: {
        'png': 64,
        'grid.json': 64,
        'mvt': 0
}
```
Furthermore we have defined default values at renderer level:
```
mapnik: 64
pg-mvt: 0
torque: 0
```

So I'd say we can close this issue, right @rafatower?

**Comment by rafatower** [comment]
This issue refers to `pgraster_datasource`, not to png layers. I'd leave it open, though not a priority.

**Comment by Algunenano** [comment]
Stale
