### ISSUE TITLE
Cleanup testing data after run

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#26]
We currently create a database and a couple of users in the PostgreSQL cluster while running tests.
It would be wise to choose pseudo-random names for both db and users, and to remove them after the test has been run.

**Comment by rochoa** [comment]
We are already dropping and creating the test database: https://github.com/CartoDB/Windshaft-cartodb/blob/2.5.0/test/support/prepare_db.sh#L70-L72
