### ISSUE TITLE
Possible error generating an image of a named map with a private table

### ISSUE THREAD

**Issue by javierarce** [CartoDB/Windshaft-cartodb#262]
We found an error generating an image of a named map with a private table:

`permission denied for relation libraries`

Here's the problematic vizjson:

`http://arce.cartodb.com/api/v2/viz/d8e40924-0ba1-11e4-b480-0e10bcd91c2b/viz.json`

And the call to the tiler: https://gist.github.com/javierarce/abc84721db107d8094ad

**Comment by rochoa** [comment]
@javierarce did you experience similar problems? If you didn't I will close this issue.

**Comment by javierarce** [comment]
No, I haven't seen that problem lately.

**Comment by rochoa** [comment]
always be closing!
