### ISSUE TITLE
Allow to request a static preview with a fixed URL based on vizjson id

### ISSUE THREAD

**Issue by javierarce** [CartoDB/Windshaft-cartodb#269]
It would be super nice to allow requesting an image using an URL like this:

`/static/vizjson/*:vizjsonid*/:width/:height.:format`

Related to: https://github.com/CartoDB/cartodb/issues/2694

**Comment by rochoa** [comment]
This needs https://github.com/CartoDB/Windshaft-cartodb/issues/287
