### ISSUE TITLE
Markers are cut at the end of the world

### ISSUE THREAD

**Issue by iriberri** [CartoDB/Windshaft-cartodb#272]
![image](https://cloud.githubusercontent.com/assets/1730320/6693039/b56f3086-ccd0-11e4-8883-67ab6933917b.png)

Is there something that we could do in this case?

**Comment by fdansv** [comment]
but is it the end... or the beginning of the world? :trolleybus:

**Comment by rochoa** [comment]
Won't fix. Sorry.
