### ISSUE TITLE
Remove QueryTables through SQL API

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#273]
That way we decouple it from the SQL API and it's no longer required to have it running.

cc @zenitraM

**Comment by rochoa** [comment]
Done in https://github.com/CartoDB/Windshaft-cartodb/pull/278

**Comment by javisantana** [comment]
I thought this ticket was not using postgres but using the parser to do this :D

**Comment by rochoa** [comment]
That's a different thing, I will file a new issue about that one.
