### ISSUE TITLE
Could we use a query parser for affected tables?

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#279]
See https://github.com/pganalyze/queryparser

Would that be enough to return affected tables? Think about queries with functions that use other tables, I think that won't be useful in those cases but probably the current approach is not solving some of those scenarios either.

cc @javisantana @zenitraM

**Comment by javisantana** [comment]
hey, one comment about functions that use tables. postgres is not able to deal with those cases so we neither, what we should do is document the way cartodb works and what are the constraints. 

That functions thing is being a blocker for us and have a pretty easy solution:

```
select CDB_SetFunctionRelatedTables('myfunction', ['table1', 'table2', 'table3']);
```

for functions that the tables used are dynamic:

```
select CDB_SetFunctionRelatedTablesFn('myfunction', 'myfunction_related_tables');
```

`myfunction_related_tables` returns an array with the tables using for the same parameters passed to myfunction

it could be more magical bug is good enough

**Comment by rochoa** [comment]
Actually the [MapConfig specification for Mapnik layers](https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.3.0.md#21-mapnik-layers-options) has an option to hint about affected tables. But it never got implemented.

**Comment by Algunenano** [comment]
Talk about things that aren't happening anytime soon
