### ISSUE TITLE
Too much simplification! 

### ISSUE THREAD

**Issue by iriberri** [CartoDB/Windshaft-cartodb#281]
I've received a map of a user where points disappeared after zooming a lot due to the simplification (I talked about it with @rochoa).

I've reproduced a map with the same CartoCSS [here](http://team.cartodb.com/u/iriberri/viz/2f3499ea-d84f-11e4-94aa-0e0c41326911/embed_map). (Zoom in once to see the issue)

As a workaround, I suggested increasing the marker-width for big levels of zoom.

**Comment by javisantana** [comment]
what is the cartocss ? there is no simplification for points AFAIK

**Comment by rochoa** [comment]
The map seems to work at all available zoom levels.
