### ISSUE TITLE
DB host or name not found in redis

### ISSUE THREAD

**Issue by lordpato** [CartoDB/Windshaft-cartodb#292]
I already tried running script/restore_redis (in fact is the first thing I run so the SQL API works.
But Windshaft still gives me the following error:

Any ideas?

"DB host or name not found in redis (try CARTODB/script/restore_redis)"

**Comment by rochoa** [comment]
Could you share what is the configuration for Redis in both cases? SQL API and Windshaft-cartodb.

**Comment by rochoa** [comment]
Feel free to reopen if you find the problem again or you can provide extra information :smile:
