### ISSUE TITLE
add global mapview counter per stat_tag

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#296]
as per https://github.com/CartoDB/Windshaft-cartodb/wiki/Redis-stats-format only stats per day are saved in visualization, it should save a new attribute with the total number of stat_tag views.

```
zincrby user:luisico:mapviews:stat_tag:12345 1 "total"
```

**Comment by lbosque** [comment]
PR: https://github.com/CartoDB/node-cartodb-redis/pull/11

**Comment by rochoa** [comment]
This was already merged :smile:
