### ISSUE TITLE
Coordinates out of range when requesting tiles at high zoom levels

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/Windshaft-cartodb#321]
See:
http://2.basemaps.cartocdn.com/light_all/10/0/1000.png <-- works
http://2.basemaps.cartocdn.com/light_all/30/0/1000.png <-- works
http://2.basemaps.cartocdn.com/light_all/31/0/1000.png <-- coords out of range

**Comment by rochoa** [comment]
Check this one: http://2.basemaps.cartocdn.com/light_all/31/1/0.png Most likely due the wrapping function for longitude coordinate.

**Comment by dgaubert** [comment]
isn't a bug It's a feature  😈 

Closing.
