### ISSUE TITLE
Issue with 32BF datatype in raster

### ISSUE THREAD

**Issue by d4weed** [CartoDB/Windshaft-cartodb#322]
I haven't found a way to represent 32BF datatype rasters other than re-classify them or running them to a function that does the same (like ST_ColorMap)

errors: ["pgraster_wkb_reader: grayscale band type 11 unsupported"]

I was wondering if there is a solution to this or we need to assume it's just unsupported

**Comment by pramsey** [comment]
You need to get out of the greyscale rendering chain and into the data rendering chain so you can apply a mapnik `RasterColorizer`. You do that by telling windshaft what `band` you want to use for your data (for a float raster, almost always band 1). When the pgraster mapnik driver sees the band parameter it'll shift into "indexed" data mode and create a data raster that mapnik will then apply the `RasterColorizer` to.

**Comment by pramsey** [comment]
Here's what a cartodb.js based page that does colorized output looked like in my case (hopefully everything this requires has now been deployed to production)
```js
function currentUser() {
    return currentEndpoint().match(/http[s]*:\/\/([^.]*).*/)[1];
}

function currentEndpoint() {
    return "http://cdb.localhost.lan:8181/api/v1/map";
}


function main() {

  // DEMUI16
  // var mycss = "#demui16 {raster-opacity: 0.5;}";
  var my_sql = "select * from demui16";
  var my_center = [59.5198659873399,15.0622475710011];
  var my_css =
    "#demui16 {raster-opacity: 0.7;" +
    "raster-colorizer-default-mode: linear;" +
    "raster-colorizer-default-color: #ff00ff;" +
    "raster-colorizer-epsilon: 0.01;" +
    "raster-colorizer-stops:" +
    " stop(0,rgba(5,255,255,255))" +
    " stop(1500,rgba(0,0,222,255)) " +
    "}" ;


    // Create map
    var map = new L.Map('map', {
        zoomControl: true,
        drawnControl: true,
        center: my_center,
        zoom: 12
     });

    // Add CartoDB basemaps
    L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
        attribution: '<a href="http://cartodb.com">CartoDB</a> © 2014',
        maxZoom: 16
    }).addTo(map);

    cartodb.createLayer(map, {
      sql_api_template: 'http://{user}.localhost.lan:8080',
      maps_api_template: 'http://{user}.localhost.lan:8181',
      user_name: 'cdb',
      type: 'cartodb',
      sublayers: [{
        sql: my_sql,
        cartocss: my_css,
        raster: true,
        raster_band: 1
      }]
    })
    .addTo(map)
}
```

**Comment by d4weed** [comment]
Awesome! It works perfectly.

Thanks a lot!

**Comment by javisantana** [comment]
\o/
