### ISSUE TITLE
Make the list of available fonts in the editor configurable

### ISSUE THREAD

**Issue by azamorano** [CartoDB/Windshaft-cartodb#330]
It would be nice to make this list of fonts configurable so they can be modified depending on the operating system CartoDB is running on, licenses, etc.

Related to https://github.com/CartoDB/cartodb/issues/5489#issuecomment-139971347

**Comment by rochoa** [comment]
Hey,

The way we enable fonts in windshaft is by registering system fonts and any other font configured, see: https://github.com/CartoDB/Windshaft/blob/0.51.0/lib/windshaft/server.js#L369-L379

As per https://github.com/CartoDB/cartodb/issues/5489 what I understand is that we want to configure the fonts that are available, don't we?

So this issues should be more about constraint the available fonts for mapnik than listing them.

p.s.: font management is being moved to windshaft-cartodb and no longer happening in windshaft so it makes sense to keep this issue in this repo.

**Comment by Algunenano** [comment]
Stale
