### ISSUE TITLE
Start adding a specific tile cache header with reduced TTL

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#334]
We should add a new cache like "X-Cache-TTL" or something similar that can be checked in varnish and apply that TTL to the object.

That way varnish will have less overhead while banning objects because a big part of the objets will be removed sooner.

copied from https://github.com/CartoDB/Windshaft/issues/224

**Comment by rochoa** [comment]
What do you think about this one @luisbosque?

**Comment by luisbosque** [comment]
Sorry, I'm not sure if I follow. What would be the difference between the TTL in this header and the one in Cache-Control?

**Comment by rochoa** [comment]
IIRC the idea was to have fewer objects in Varnish, by making the invalidation process easier and more frequent.

**Comment by Algunenano** [comment]
Stale
