### ISSUE TITLE
Add a success response back when you delete a named map

### ISSUE THREAD

**Issue by csobier** [CartoDB/Windshaft-cartodb#347]
Right now, there is no success response back, just an error message if it's not correct. Can you add a success response back when you delete a named map? 

@rochoa ,  this request is a result of a Support issue. Please advise if this is possible? (I am happy to coordinate doc updates once the code updated).

**Comment by rochoa** [comment]
From https://github.com/CartoDB/Windshaft-cartodb/blob/4f4480dc9bdd65f1d6662534247372d2e42df649/docs/named_maps.md#delete

> On success, a 204 (No Content) response will be issued. Otherwise a 4xx response with an error will be returned.

So that's the expected behaviour.
