### ISSUE TITLE
Add limit to docs for named maps

### ISSUE THREAD

**Issue by eightysteele** [CartoDB/Windshaft-cartodb#353]
Named maps have a limit of 4096. If users need more, they probably want to use templates.

**Comment by csobier** [comment]
@eightysteele , I added this to the MAPS API content. Just waiting for the merge.  Thanks!

**Comment by eightysteele** [comment]
@csobier haha I think I beat you to it in #354 :dancer: 

Should I close that PR so we're not duplicating?

**Comment by csobier** [comment]
Yes, please :-)

**Comment by eightysteele** [comment]
Done :)

**Comment by csobier** [comment]
Thanks. I'll close this issue once I verify the changes are appearing live.

**Comment by eightysteele** [comment]
+1
