### ISSUE TITLE
Inject a query identifier on database queries sent to Mapnik

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/Windshaft-cartodb#357]
The idea is to cross-check timings all over the stack.

Once we compile node-mapnik with a mapnik built from https://github.com/CartoDB/mapnik-packaging/pull/1, it will output to stdout all queries performed by Mapnik.

However, we need to cross-reference them with the HTTP requests logged on the Windshaft logs.

A way to do this could be injecting the ID as a comment on the beginning of the user-supplied query, for example:
`/*QUERY_ID:uuid-comes-here*/SELECT * FROM...`

This Query_ID should be:
- logged on the tiler log
- (maybe) returned as a header on the response?

There is a X-Request-ID header coming on all HTTP requests done from our front balancers, but due to metatiling, a single query might be used to serve more than one tile request

**Comment by dgaubert** [comment]
@rafatower @Algunenano 

have we done something similar to correlate HTTP requests and queries?

**Comment by Algunenano** [comment]
No, there has been talks about having more controls over the final query sent from Mapnik to Postgresql but nothing about matching HTTP request with queries. We are already getting the time spent in the DB per request, but I don't know if that's enough. Can you give an example where it would be useful to get these queries as part of the output?

Also keep in mind that Mapnik doesn't necessarily do just one query: per layer it might do 1 query to get the columns (LIMIT 0) plus N (depending on the style and the settings, although we are now optimizing them to reuse them when possible). So you are looking into a matrix of queries, not just one.

**Comment by dgaubert** [comment]
I think that the final goal of this issue is to know how long a query takes to be executed and the rendering time. Despite we don't have HTTP request correlated we have metrics about query-time vs rendering-time.

Do you know other requirements??

**Comment by Algunenano** [comment]
No longer necessary.
