### ISSUE TITLE
vector tiles should send only the needed columns

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#378]
if I have a layer with sql `select * from table` and that table has 300 columns vector tiles are sent with those 300 columns. That is a performance problem because of the tile size.

The proposal is to send only the needed columns, that's it, the ones in:
- cartocss, for example if we have `[attr < 10]{ ....}` the column `attr` should be sent
- widgets: any column used in widgets should be sent to calculate stuff
- interactivity ones

I think this is valid for geojson and MVT.

- [x] GeoJSON.
- [ ] MVT.

cc @rochoa

**Comment by dgaubert** [comment]
- [x] GeoJSON renderer [Windshaft #458](https://github.com/CartoDB/Windshaft/pull/458)

**Comment by javisantana** [comment]
this is working, right?

**Comment by dgaubert** [comment]
Yes, it is.

**Comment by rochoa** [comment]
Well, not for MVT. Just for geojson.

**Comment by rafatower** [comment]
It is implemented in the ST_AsMvt renderer. I'm not sure whether this is still needed or pressing but I'm closing this FTM. We can reopen it if needed
