### ISSUE TITLE
Overviews information not added for instantiated templates

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#402]
In the maps controller (lib/cartodb/controllers/map.js) in `instantiateTemplate`, [`addOverviewsInformation`](https://github.com/CartoDB/Windshaft-cartodb/blob/fc94f3ad942ffcd9df5fca3e20ab1010e0788f44/lib/cartodb/controllers/map.js#L243) expects `requestMapConfig`to be a plain JSON object (with a `layers` attribute), but `NamedMapMapConfigProvider` passes a `MapConfig` to it instead.

A simple workaround is to replace the uses of `requestMapConfig` by `requestMapConfig._cfg`, 
but that's an internal detail of `MapConfig`.

Note that there's another issue that prevents named maps from using overviews here: https://github.com/CartoDB/cartodb/issues/6916

**Comment by rochoa** [comment]
The solution could be similar to the current one used for turbo-cartocss: https://github.com/CartoDB/Windshaft-cartodb/blob/fc94f3ad942ffcd9df5fca3e20ab1010e0788f44/lib/cartodb/models/mapconfig/named_map_provider.js#L95-L110

**Comment by jgoizueta** [comment]
Duplicate of #400
