### ISSUE TITLE
Vector tile should have object id (cartodb_id)

### ISSUE THREAD

**Issue by jaakla** [CartoDB/Windshaft-cartodb#408]
MVT has special field for object ID-s, currently it seems to remain empty. It should have cartodb_id value, then renderer knows that certain object is same on different zooms and it can be rendered in nicer way (without "flickering" issues).

@mtehver can comment more

**Comment by rochoa** [comment]
Is this problem still present?

**Comment by jaakla** [comment]
@rochoa can you give any working vector tile URL with some data, so I could check?

**Comment by rochoa** [comment]
I thought you had some specific cases that were failing.

**Comment by jaakla** [comment]
It was general issue with any mvt. I tried now http://ashbu.cartocdn.com/nutiteq/api/v1/map/nutiteq@e1ff8396@877eff9a911efca2184fc2fad6466e8e:1484925489996/1,2,3,4,5,6/18/42274/101735.mvt which seems to have ID-s for objects now, but these seem to be 64-bit ints, so I'm not sure if the value is really same as cartodb_id in the database?
```
../git/vector-tile-py/tile-raw-info.py carto-101735.mvt 
layers: 2
6d9ff0d2-775e-46cb-92ec-47b9169a6f56:
  version: 2
  extent: 4096
  features: 16
  keys: 20
  values: 107
  geometry summary:
    total: 292
    commands: 48
    move_to: 16
    line_to: 106
    close: 16
    degenerate polygons: 16
    empty geoms: 0
ecc74619-c6f4-4618-9efe-f489910d2aa3:
  version: 2
  extent: 4096
  features: 12
  keys: 7
  values: 53
  geometry summary:
    total: 36
    commands: 12
    move_to: 12
    line_to: 0
    close: 0
    degenerate polygons: 0
    empty geoms: 0
```

**Comment by jaakla** [comment]
Correction: these 64-bit IDs are there Layer ID-s, not object ones. The object ID-s seem to be there, but the values are sequential within tile (1,2,3...) , not cartodb_id values. So this issue still persists. Sample of same tile with object details:
```
  feature: 1
    type: Polygon
    tags: 0,0,1,1,2,2,3,3,4,4,5,5,6,3,7,6
    geometries: 9,7072,8676,74,63,706,439,35,44,583,133,15,15,252,1147,81,15,178,973,123,20,357,15
  feature: 2
    type: Polygon
    tags: 0,7,2,8,4,4,5,5,8,9,9,10,7,6
    geometries: 9,4072,8714,50,247,251,156,0,5,225,178,5,0,232,166,0,15
...
```

**Comment by Algunenano** [comment]
Stale.

This is not supported by Mapnik (it autogenerates the ids) and only supported by Postgis 3+, which we don't support yet. The solution is to include cartodb_id as a property in the tiles.
