### ISSUE TITLE
row_limit should be applied to tiles, not metatiles

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#415]
When using metatiles (`metatile` parameter greater than 1), the `row_limit` applies to the whole metatile, not to each tile. This may be too low in some situations. Specifically, overviews are computed assuming a row_limit of 65536 per tile, not per metatile.

The next map, which shows a metatile layer, has been rendered with `metatile=1`, and it appears correctly:

![cabs4 - cartodb](https://cloud.githubusercontent.com/assets/5909/14509478/d1d8ee10-01cc-11e6-9cef-08430e2e7287.png)

Now, this is the result with `metatile=2`. As can bee seen, one metatile (4 tiles) is now over the row limit and appears incomplete:

![cabs4 - cartodb_metatile_2](https://cloud.githubusercontent.com/assets/5909/14509528/008d221c-01cd-11e6-94bb-03c007b26eb7.png)

**Comment by jgoizueta** [comment]
cc @javisantana @rafatower

**Comment by jgoizueta** [comment]
We could just pass `row_limit*metatile*metatile` as the actual row_limit to Mapnik. Could this be too large in some cases?

**Comment by pnorman** [comment]
> We could just pass `row_limit*metatile*metatile` as the actual row_limit to Mapnik. Could this be too large in some cases?

Averaged over the metatile this will be the same, and rendering one image of `metatile^2*row_limit` rows is less work than rendering `metatile^2` images of `row_limit` rows.

**Comment by jgoizueta** [comment]
It seems we are not having a row_limit currently in production: https://github.com/CartoDB/cartodb-platform/blob/develop/cookbooks/node-windshaft/attributes/default.rb#L76

So this should not be a problem in production ATM.

**Comment by rochoa** [comment]
Both parameters can be tweaked at configuration so you can decide if you want to go with the `row_limit*metatile*metatile` or any other value.
