### ISSUE TITLE
Allow basic filtering in overviews queries

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#428]
Currently when (vector) overviews exist for a table, they're used in the query passed to Mapnik only if the original query is of a very simple form not having a WHERE clause.

Allow the queries to have a simple (no joins, subselections, etc.) WHERE clause and apply it to the query passed to the tiler.

**Comment by rafatower** [comment]
as per jgoizueta: superseeded by the ticket about widgets, closing this
