### ISSUE TITLE
Named maps static map API not working after making a dashboard

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/Windshaft-cartodb#450]
Hey @rochoa 

I am trying to use the static maps api with a named map like you describe here : 

https://github.com/CartoDB/Windshaft-cartodb/pull/443

It was working like a charm but then I loaded the map in the new editor and made a dashboard. This seems to have broken the static images that I was linking to before. Not sure whats happening.

Dashboard is here : https://observatory.cartodb.com/editor/5de68840-16ef-11e6-bf4f-0ea31932ec1d/embed and the static image urls I am trying to get are 

https://observatory.cartodb.com/api/v1/map/static/named/tpl_5de68840_16ef_11e6_bf4f_0ea31932ec1d/300/300.png?bbox=-87.940102,41.643917,-87.523979,42.023026

https://observatory.cartodb.com/api/v1/map/static/named/tpl_5de68840_16ef_11e6_bf4f_0ea31932ec1d/300/300.png?bbox=-74.259094,40.477398,-73.700165,40.91758

Not sure if I have done something wrong or the new editor made some change to the viz json or something.

Cheers

**Comment by rochoa** [comment]
This is definitely a bug related to new analyses features. The named map is OK, so this is the right place to track this issue.

Hope to have a fix sooner than later.
