### ISSUE TITLE
Dataviews unified with Windshaft's widgets

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#464]
As a way to reduce the number of options in terms of dataviews vs. layers+widgets it would be really nice to adapt the later to the former so everything becomes a dataview and it's handled by Windshaft-cartodb's dataviews instead of Windshaft's widgets.

This change could become backwards incompatible if cartodb.js has somehow hardcoded handling of metadata instead of being a bit loose/vague allowing any of the two metadata formats for widget/dataviews.

cc/ @alonsogarciapablo 

Ref. https://github.com/CartoDB/deep-insights.js/issues/358

**Comment by alonsogarciapablo** [comment]
CartoDB.js [will try to get metadata from dataviews and fallback to layer+widgets from the response](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/map-base.js#L132-L149). From that POV I think it should work fine.

**Comment by rochoa** [comment]
This was done at https://github.com/CartoDB/Windshaft-cartodb/pull/485
