### ISSUE TITLE
Analyses are not "cached" between map instantiations

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#474]
This issue comes from CartoDB/cartodb#7523.

**Steps to reproduce:**

1. Create an instance of a map with an analysis that will take some time (eg: a point in polygon).
2. Verify that analysis has the "pending" status in the Maps API response.
2. Wait until analysis is "ready".
3. Create an instance of the map again using the same payload you used for 1.

**Expected result:**
- Analysis node has "ready" status in the response from the Maps API.

**Actual result:**
- Analysis node has "pending" status again in the response from the Maps API.

cc: @javisantana @viddo @rochoa

**Comment by rochoa** [comment]
This was fixed at https://github.com/CartoDB/Windshaft-cartodb/pull/477.
