### ISSUE TITLE
Torque/Torque Cat + Animated Heatmap named map not properly rendered.

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/Windshaft-cartodb#492]
STR:

1. Create a map with two layers: A torque or torque cat and an animated heat map.
2. Make sure datasets are private (so a named map is generated for the embed)
3. Access embed

Expected result:

- Both layers are animated and shown as in the editor view.

Actual result:

- Heatmap is OK, but toruqe/torque cat points are shown clustered on the edges of invisible squares.

I've checked both sql in templates and they seem ok.

Here is a capture of the result:

![tiler_bug](https://cloud.githubusercontent.com/assets/4222826/15853806/ea638526-2ca6-11e6-8de2-c8e80285695f.gif)

cc/ @rochoa

**Comment by rochoa** [comment]
Can you attach an screenshot of the actual/incorrect result?

**Comment by gfiorav** [comment]
I've added it to the issue description :)

**Comment by gfiorav** [comment]
fixed in the new editor, old editor is not maintained. Thanks!
