### ISSUE TITLE
Null category with 0 count

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#497]
![687474703a2f2f692e696d6775722e636f6d2f43396473504b622e706e67](https://cloud.githubusercontent.com/assets/45346/14313819/1dcc8522-fbf4-11e5-968f-61d662712e42.png)

![687474703a2f2f692e696d6775722e636f6d2f666142527578322e706e67](https://cloud.githubusercontent.com/assets/45346/14313834/2d662ed4-fbf4-11e5-879d-f578b23d236f.png)

ref https://github.com/CartoDB/deep-insights.js/issues/269

replaces https://github.com/CartoDB/Windshaft/issues/468

**Comment by jorgesancha** [comment]
Adding to TODO column in Engine

**Comment by dgaubert** [comment]
I've just pushed a [test](https://github.com/CartoDB/Windshaft-cartodb/commit/f5f0601e53cd5cd90f46713fba12595396e10446) to check if category NULL count its values properly. It just passed. :man_shrugging:

@AbelVM, could you share your dataset to take a look?

**Comment by AbelVM** [comment]
6 months later... Nope, I'm afraid I don't have the dataset above :disappointed:

**Comment by dgaubert** [comment]
No problem, thanks for your patient...

**Comment by dgaubert** [comment]
Ready for CR in #617

**Comment by ethervoid** [comment]
@dgaubert could you please add some acceptance steps to pass it? thank you!

**Comment by dgaubert** [comment]
Sure thing!

1. Go to cartodb-staging.com
2. Create a map using populated_places dataset.
3. Create a category widget with adm0name as aggregation column and count operation:
![screen shot 2017-01-19 at 16 38 41](https://cloud.githubusercontent.com/assets/1936888/22113207/d1cd580e-de65-11e6-9f50-15dca03ba9eb.png)
Should look like:
![screen shot 2017-01-19 at 16 40 50](https://cloud.githubusercontent.com/assets/1936888/22113308/1bad0cc6-de66-11e6-8957-80391eaf2632.png)
4. Change operation to SUM over `pop_max`column, should look like:
![screen shot 2017-01-19 at 16 57 43](https://cloud.githubusercontent.com/assets/1936888/22114063/8581f40c-de68-11e6-810a-ac454bba6ef9.png)
5. Update dataset, lets put some null values: `UPDATE ne_10m_populated_places_simple SET pop_max = NULL WHERE adm0name = 'India' and pop_max > 500000`. Now widget should look like:
![screen shot 2017-01-19 at 17 14 53](https://cloud.githubusercontent.com/assets/1936888/22114791/fba015fe-de6a-11e6-89d0-f92ead0cb788.png)
6. Update adm0name = 'India' to NULL: `UPDATE ne_10m_populated_places_simple SET adm0name = NULL WHERE adm0name = 'Brazil'`. Widget:
![screen shot 2017-01-19 at 17 21 08](https://cloud.githubusercontent.com/assets/1936888/22115037/c3bd928c-de6b-11e6-803f-bc544d70aa46.png)

Hope this help.

**Comment by dgaubert** [comment]
I forgot that I've implemented test that covers this bugfix. So, there is no need to do it manually.

skipping acceptance step.
