### ISSUE TITLE
Logs tagged with request types

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#508]
It would be nice if all requests logs were tagged with the request type:
- Named maps admin
- Map view/creation
- Tiles
- Attributes
- Dataviews
- Static maps

**Comment by kidwellj** [comment]
+1 on this. Would offer some especially useful ways to track user engagement especially if logfiles notated tile bounds and zoom level.

**Comment by dgaubert** [comment]
Opening a 🍈 ...

We use `bunyan` in modules like `camshaft`. Have you thought on migrate current logger to `bunyan` as well?. If so ... https://github.com/CartoDB/metallic-logger

🤗

**Comment by Algunenano** [comment]
Stale
