### ISSUE TITLE
Test effects of style GET parameter on POST style calls

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#52]
I suspect that passing a ``style`` parameter in the URL while POST'ing to /style is going to have wild side-effects.

In particular I think that an ``mml_builder`` is initialized to have a "custom style" extended key and so at the time of the .setStyle method invocation it ends up being deleted by effect of "drop related keys".

Doesn't seem to be harmful, just wild, in that I dubt the redis caches for extended style are meant to be drop when the default table style is changed, nor it would make sense to drop a key while trying to set its style

**Comment by rochoa** [comment]
Old API method will be deprecated (https://github.com/CartoDB/Windshaft-cartodb/issues/257), when that happens this doesn't make sense anymore.
