### ISSUE TITLE
Simplify error message for turbo-carto errors (with context)

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#544]
turbo-carto errors now have the following format:

```
{
  "type": "layer",
  "message": "turbo-carto: Unable to process \"polygon-fill\". Reason: Unable to compute ramp. Reason: column \"asdsf\" does not exist. Context: {\"selector\":\"#layer\",\"source\":{\"start\":{\"line\":2,\"column\":3},\"end\":{\"line\":2,\"column\":66}}}",
  "http_status": 400,
  "subtype": "turbo-carto",
  "layer": {
    "id": "ef0fe0d2-e7d2-432b-a603-82a33fe72be5",
    "index": 0,
    "type": "cartodb",
    "context": {
      "selector": "#layer",
      "source": {
        "start": {
          "line": 2,
          "column": 3
        },
        "end": {
          "line": 2,
          "column": 66
        }
      }
    }
  }
}
```

I noticed that the `message` key is not very human readable and includes things like the context (which is also specified inside `layer.context`:

`"turbo-carto: Unable to process \"polygon-fill\". Reason: Unable to compute ramp. Reason: column \"asdsf\" does not exist. Context: {\"selector\":\"#layer\",\"source\":{\"start\":{\"line\":2,\"column\":3},\"end\":{\"line\":2,\"column\":66}}}"`

Could we simplify the message to something like `Unable to compute ramp: column "asdsf" does not exist`?

cc: @rochoa @dgaubert

**Comment by rochoa** [comment]
What if ...

```css
#layer {
  marker-fill: ramp([asdsf], colorbrewer(Reds));
  marker-width: ramp([asdsf], 2, 16);
}
```

How do I know what the error is?

Should we use different messages for `{ "errors": [] }` and `{ "errors_with_context": [] }`?

**Comment by alonsogarciapablo** [comment]
`Unable to compute ramp for "marker-fill" property: column "asdsf" does not exist` ... 😄 

> Should we use different messages for { "errors": [] } and { "errors_with_context": [] }?

I think they can be the same.

**Comment by rochoa** [comment]
If we use the same error messages older clients won't get the full context in the error message.

So basically you are asking for an error message without context, right?

**Comment by dgaubert** [comment]
context is added in [turbo-carto](https://github.com/CartoDB/turbo-carto/blob/master/src/helper/turbo-carto-error.js#L11) to error's message. Should we parse it in Windshaft-cartodb?

**Comment by alonsogarciapablo** [comment]
> So basically you are asking for an error message without context, right?

Yes, a more user friendly that we can display in the UI right now:

<img width="594" alt="screen shot 2016-07-05 at 18 28 40" src="https://cloud.githubusercontent.com/assets/390398/16611589/960e91b4-4362-11e6-8c9d-a636bcc38f96.png">

☝️ this is what we see now. Either we change the message that Windshaft-CartoDB returns, or we provide more context (in the `context` property) and generate that message on the UI (which will need to do for example if we decide to translate the UI)..

**Comment by alonsogarciapablo** [comment]
cc: @xavijam ☝️

**Comment by xavijam** [comment]
It would be great yeah

**Comment by dgaubert** [comment]
> context is added in turbo-carto to error's message. Should we parse it in Windshaft-cartodb?

I mean, every turbo-carto error comes with context, so it would be easy to remove context in both Windshaft-cartodb & front-end.

**Comment by dgaubert** [comment]
Closing. Reopen if needed
