### ISSUE TITLE
Add show/hide support for layers

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#550]
Windshaft has partial support: it allows to filter mostly all layer types, except Mapnik layers, where you only can hide or show all of them.

## Current workaround

Current templates look like:

```json
{
  "template": {
    "auth": {
      "method": "open"
    },
    "version": "0.0.1",
    "name": "hide-layers-example",
    "placeholders": {
      "layer0": {
        "type": "number",
        "default": 1
      },
      "layer1": {
        "type": "number",
        "default": 1
      }
    },
    "layergroup": {
      "layers": [
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png"
          }
        },
        {
          "type": "cartodb",
          "options": {
            "sql": "SELECT * FROM (select * from table_a) AS wrapped_query WHERE <%= layer0 %>=1",
            "layer_name": "provinces_tourists",
            "cartocss": "...",
            "cartocss_version": "2.3.0"
          }
        },
        {
          "type": "cartodb",
          "options": {
            "sql": "SELECT * FROM (select * from table_b) AS wrapped_query WHERE <%= layer1 %>=1",
            "cartocss": "...",
            "cartocss_version": "2.3.0"
          }
        },
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_labels/{z}/{x}/{y}.png"
          }
        },
        {
          "type": "torque",
          "options": {
            "sql": "select * from torque_table_a",
            "cartocss": "...",
            "cartocss_version": "1.0.0"
          }
        }
      ]
    }
  }
}
```

The workaround to hide a mapnik layers, in general layers with SQL queries, is to instantiate the map with different values for params `layer0` and `layer1`. This requires having all layers with wrapped queries like above. However, this approach is inefficient/limited because:
 - You have to instantiate the map each time you want to show/hide a layer.
 - Internally the layer is still present, and the query has to run to not retrieve data.
 - If one of the layers doesn't have that clever trick it's not possible to hide it.
 - If SQL is provided by an analysis it won't have the trick.

So it's clear we need a way to show/hide layers.

## Current solution

Right now it's possible to render specific layers specifying their layer index.

 - `GET /api/v1/map/{layergroupid}/0/1/1/0.png` will render the basemap layer.
 - `GET /api/v1/map/{layergroupid}/3/1/1/0.png` will render the labels layer.
 - `GET /api/v1/map/{layergroupid}/4/1/1/0.png` will render the torque layer.

It's even possible to select multiple layers:

 - `GET /api/v1/map/{layergroupid}/0,3,4/1/1/0.png` will render basemap, labels, and torque layers.

And there are aliases:

 - `GET /api/v1/map/{layergroupid}/all/1/1/0.png` will render all layers together.
 - `GET /api/v1/map/{layergroupid}/mapnik/1/1/0.png` will render all mapnik layers.

### Limitations

However currently it's not possible to render mapnik layers independently: `GET /api/v1/map/{layergroupid}/1/1/1/0.png` will render all mapnik layers, although it is requesting just layer with index=1. So it is the same as `GET /api/v1/map/{layergroupid}/mapnik/1/1/0.png`, or `GET /api/v1/map/{layergroupid}/2/1/1/0.png`, or `GET /api/v1/map/{layergroupid}/1,2/1/1/0.png`.

### Missing features

 - More than a limitation, but an agreed decision, it's not possible to alter the ordering. Layers are always rendered based on the layer ordering of the named map.
 - There are no aliases for other layer types but mapnik one.

## Proposal

To continue with that approach of being able to show/hide layers by requesting the different layer indexes in the URL, we will:

 - Fix the current limitation with mapnik layers: so it's possible to render layers independently.
 - Allow to use [layer id](https://github.com/CartoDB/Windshaft/blob/a398bd4f2c7c4d7e9f582e8d2ff1fb118f1af8ba/doc/MapConfig-1.5.0.md#2-file-format) as an alternative to current layer index. `GET /api/v1/map/{layergroupid}/1,2/1/1/0.png` could become `GET /api/v1/map/{layergroupid}/layer0,layer1/1/1/0.png`. This requires to constraint layer ID to not be numeric, and cannot be `all`, `mapnik`, or in general any layer type.

Extra features we could do but we will leave out for future improvements:
 - Create aliases for different layer types as the one we have for mapnik type.
 - Allow layer reordering.

## Alternative

In order to support the hide/show for all layer types we could change the instantiation of the named map to specify what layers we want to have in the map instance, so we could drop some mapnik layers. We wouldn't need to change any low-level component (Windshaft) but it's adding a new functionality that can be solved by fixing/improving a solution that is already working. And we will require to re-instantiate the map each time we need to show/hide a layer, which is far from ideal from the client perspective.

Related issues:
 - https://github.com/CartoDB/cartodb/issues/7918
 - https://github.com/CartoDB/Windshaft/issues/477

cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Thanks for the (great) write up!

👍 to your proposal!

**Comment by rochoa** [comment]
This is already finished, right @dgaubert?

**Comment by dgaubert** [comment]
Yup!
