### ISSUE TITLE
Torque not working due to clash of column name with tile sql query

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/Windshaft-cartodb#558]
We have an issue when the user's dataset for example has a column named `d`. The problem is that in the [tile_sql](https://github.com/CartoDB/Windshaft/blob/7a2bf2c6cc3259fede0e07b2f8b5f91d9fa5a82c/lib/windshaft/renderers/torque/renderer.js#L132) query there is a column called `d` used in the group by and we have a clash between the two. I think this is extensible to columns like xx or yy used in that query too.

Another thing is that we aren't reflecting this error in the tile console log or in the UI. This response comes from this GET request:

```
Request URL:http://ethervoid.localhost.lan:8181/api/v1/map?config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%22bf8ab7c6-4a6e-11e6-9780-080027eb929e%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22torque%22%2C%22options%22%3A%7B%22cartocss_version%22%3A%221.0.0%22%2C%22cartocss%22%3A%22Map%7B-torque-frame-count%3A256%3B-torque-resolution%3A2%3B-torque-aggregation-function%3A%27count(cartodb_id)%27%3B-torque-time-attribute%3A%27time%27%3B-torque-data-aggregation%3Alinear%3B%7D%22%2C%22sql%22%3A%22select%20*%20from%20untitled_table_6%22%7D%7D%5D%7D&callback=_cdbct_49335909_1&stat_tag=bf8ab7c6-4a6e-11e6-9780-080027eb929e&map_key=bfd55fceb9be2ee675007c470885a75bc9ed9915
```
but we're getting a 200 HTTP response with this inside:

```
/**/ typeof _cdbct_49335909_1 === 'function' && _cdbct_49335909_1({"errors":["TorqueRenderer: column \"i.time\" must appear in the GROUP BY clause or be used in an aggregate function"],"errors_with_context":[{"type":"unknown","message":"TorqueRenderer: column \"i.time\" must appear in the GROUP BY clause or be used in an aggregate function","name":"error","length":163,"severity":"ERROR","code":"42803","position":"985","file":"parse_agg.c","line":"1328","routine":"check_ungrouped_columns_walker"}]});
```

Example file [untitled_table_6.csv.zip](https://github.com/CartoDB/Windshaft-cartodb/files/365645/untitled_table_6.csv.zip)

**Comment by rochoa** [comment]
Duplicates https://github.com/CartoDB/cartodb/issues/3160.

Tracking at https://github.com/CartoDB/Windshaft/issues/317.
