### ISSUE TITLE
GeoJSON vector tiles should send coordinates in lonlat

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/Windshaft-cartodb#566]
As per the [new recommendation](https://sgillies.net/2016/08/11/rfc-7946-the-geojson-format.html):

> Coordinate reference systems are no longer in the core of the specification; use CRS84 longitude and latitude with GeoJSON from now on.

For instance, GeoJSON tiles will not work properly with Tangram because of this (confirmed with Mapzen):

http://bl.ocks.org/danicarrion/c58951c4685993d57c0317de161c8825

**Comment by rochoa** [comment]
We send it with `lon,lat` format but we use EPSG:3857 as default as per `"srid": 3857` in https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.5.0.md.
