### ISSUE TITLE
log_filename configuration should work with absolute paths

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#570]
When setting the `log_filename` config to an absolute path the application points something like:

```
Logs will be written to /tmp/absolute-path.log
```

But the log is never written from the application.

**Comment by dgaubert** [comment]
Reading [log4js' documentation](https://github.com/CartoDB/log4js-node#configuration) we are using `cwd` option:

> If you have already defined an absolute path for one of the FileAppenders in the configuration file, you could add a "absolute": true to the particular FileAppender to override the cwd option passed.

We use appenders with relative paths and set `cwd` to `__dirname`. So we have two options:
    - Remove `cwd` option and each appender should define its own path (absolute or relative).
    - Add `"absolute": true` for those appenders that use absolute paths.

@rochoa do you want me to resolve this?

**Comment by dgaubert** [comment]
If we use `>=node v0.11.2`, we'll have  [path.isAbosolute()](https://nodejs.org/api/path.html#path_path_isabsolute_path) to know when to use `"absolute": true` option for each appender.
