### ISSUE TITLE
Categories query should order by count and category name

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft-cartodb#581]
In order to avoid those problems in the builder.

![screen shot 2016-10-20 at 19 36 02](https://cloud.githubusercontent.com/assets/132146/19573190/7d16b3d4-9705-11e6-8204-934446abf5d6.png)

cc @rochoa 
:kiss:

**Comment by dgaubert** [comment]
Hey @xavijam, could you share the `.carto` of this use case?

**Comment by dgaubert** [comment]
It is the expected behaviour, isn't it?
![screen shot 2016-10-26 at 11 52 18](https://cloud.githubusercontent.com/assets/1936888/19721522/dff09a9e-9b72-11e6-8452-cc9110cfc18c.png)

**Comment by dgaubert** [comment]
Fixed in [2.80.2](https://github.com/CartoDB/Windshaft-cartodb/releases/tag/2.80.2).
