### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by nicoali** [CartoDB/Windshaft-cartodb#582]
I've this issue tryng to install Windshaft-cartodb on Ubuntu 16.04 on a Raspberrypi
using node v0.10.48 and npm  v2.15.1

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/home/carto/.nvm/v0.10.48/bin/node" "/home/carto/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mapnik@1.4.15-cdb10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@1.4.15-cdb10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/carto/Windshaft-cartodb/npm-debug.log
carto@carto-desktop:~/Windshaft-cartodb$ sudo pico  /home/carto/Windshaft-cartodb/npm-debug.log

This is the log
http://www.gisna.altervista.org/npm-debug.log

**Comment by dgaubert** [comment]
We do not support Ubuntu 16.04. Please review [install guide](https://github.com/CartoDB/Windshaft-cartodb/blob/master/INSTALL.md).

HTH.

**Comment by nicoali** [comment]
ok thanks the same. Do you support ubuntu 14.04?
because there is:
On Ubuntu 14.04 the dependencies can be installed with....

**Comment by dgaubert** [comment]
Yes, we do.

**Comment by dgaubert** [comment]
Please, let us know if Windshaft runs properly on Raspberrypi.

**Comment by nicoali** [comment]
i'll try to run it :)

I'll try to compile mapnik that is the only package that fail :(

2016-10-25 17:59 GMT+02:00 Daniel <notifications@github.com>:

**Comment by nicoali** [comment]
i installed mapnik 
carto@carto-desktop:~$ mapnik-config -v
3.0.9

Now i've v.3.0.9 running on my raspberry but npm installation of windshaft still fail because i don't have npm of mapnik.

Is there anyway in the code to use the bin of mapnik and not the npm?

**Comment by nicoali** [comment]
i think i'm very close

in the log i've this:

with npm list i can see that i've installed :
http://pastebin.com/SD6cHexn

While for windshaft i've this log problem:

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/home/carto/.nvm/v0.10.26/bin/npm',
1 verbose cli   'install',
1 verbose cli   '[windshaft]' ]
2 info using npm@2.15.1
3 info using node@v0.10.26
4 verbose install initial load of /home/carto/Windshaft-cartodb/package.json
5 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/body-parser/package.json
6 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/camshaft/package.json
7 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/cartodb-psql/package.json
8 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/cartodb-query-tables/package.json
9 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/cartodb-redis/package.json
10 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/debug/package.json
11 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/dot/package.json
12 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/express/package.json
13 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/fastly-purge/package.json
14 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/istanbul/package.json
15 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/jshint/package.json
16 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/log4js/package.json
17 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/lru-cache/package.json
18 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/lzma/package.json
19 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/mocha/package.json
20 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/nock/package.json
21 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/node-mapnik_3.5.13+dfsg-1_armhf.deb/package.json
22 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/node-pre-gyp/package.json
23 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/node-statsd/package.json
24 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/queue-async/package.json
25 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/redis/package.json
26 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/redis-mpool/package.json
27 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/request/package.json
28 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/semver/package.json
29 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/step/package.json
30 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/step-profiler/package.json
31 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/strftime/package.json
32 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/turbo-carto/package.json
33 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/underscore/package.json
34 verbose installManyTop reading scoped package data from
/home/carto/Windshaft-cartodb/node_modules/yargs/package.json
35 info package.json cartodb-psql@0.6.1 No license field.
36 info package.json dot@1.0.3 No license field.
37 info package.json fastly-purge@1.0.1 No license field.
38 info package.json jshint@2.6.3 No license field.
39 info package.json mocha@1.21.5 No license field.
40 info package.json node-statsd@0.0.7 No license field.
41 info package.json queue-async@1.0.7 No license field.
42 info package.json redis@0.8.6 No license field.
43 info package.json redis-mpool@0.4.0 No license field.
44 info package.json semver@1.1.4 license should be a valid SPDX license
expression
45 info package.json strftime@0.8.4 No license field.
46 info package.json underscore@1.6.0 No license field.
47 verbose readDependencies loading dependencies from
/home/carto/Windshaft-cartodb/package.json
48 verbose readDependencies npm-shrinkwrap.json is overriding dependencies
49 info shrinkwrap file "/home/carto/Windshaft-cartodb/npm-shrinkwrap.json"
50 verbose readDependencies returned deps { 'body-parser': '
https://registry.npmjs.org/body-parser/-/body-parser-1.14.2.tgz',
50 verbose readDependencies returned deps   camshaft: '
https://registry.npmjs.org/camshaft/-/camshaft-0.46.1.tgz',
50 verbose readDependencies returned deps   'cartodb-psql': '
https://registry.npmjs.org/cartodb-psql/-/cartodb-psql-0.6.1.tgz',
50 verbose readDependencies returned deps   'cartodb-query-tables': '
https://registry.npmjs.org/cartodb-query-tables/-/cartodb-query-tables-0.1.0.tgz
',
50 verbose readDependencies returned deps   'cartodb-redis': '
https://registry.npmjs.org/cartodb-redis/-/cartodb-redis-0.13.1.tgz',
50 verbose readDependencies returned deps   debug: '
https://registry.npmjs.org/debug/-/debug-2.2.0.tgz',
50 verbose readDependencies returned deps   dot: '
https://registry.npmjs.org/dot/-/dot-1.0.3.tgz',
50 verbose readDependencies returned deps   express: '
https://registry.npmjs.org/express/-/express-4.13.4.tgz',
50 verbose readDependencies returned deps   'fastly-purge': '
https://registry.npmjs.org/fastly-purge/-/fastly-purge-1.0.1.tgz',
50 verbose readDependencies returned deps   log4js: 'git://
github.com/cartodb/log4js-node.git#145d5f91e35e7fb14a6278cbf7a711ced6603727
',
50 verbose readDependencies returned deps   'lru-cache': '
https://registry.npmjs.org/lru-cache/-/lru-cache-2.6.5.tgz',
50 verbose readDependencies returned deps   lzma: '
https://registry.npmjs.org/lzma/-/lzma-2.3.2.tgz',
50 verbose readDependencies returned deps   'node-statsd': '
https://registry.npmjs.org/node-statsd/-/node-statsd-0.0.7.tgz',
50 verbose readDependencies returned deps   'queue-async': '
https://registry.npmjs.org/queue-async/-/queue-async-1.0.7.tgz',
50 verbose readDependencies returned deps   'redis-mpool': '
https://registry.npmjs.org/redis-mpool/-/redis-mpool-0.4.0.tgz',
50 verbose readDependencies returned deps   request: '
https://registry.npmjs.org/request/-/request-2.62.0.tgz',
50 verbose readDependencies returned deps   step: '
https://registry.npmjs.org/step/-/step-0.0.6.tgz',
50 verbose readDependencies returned deps   'step-profiler': '
https://registry.npmjs.org/step-profiler/-/step-profiler-0.3.0.tgz',
50 verbose readDependencies returned deps   'turbo-carto': '
https://registry.npmjs.org/turbo-carto/-/turbo-carto-0.18.0.tgz',
50 verbose readDependencies returned deps   underscore: '
https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz',
50 verbose readDependencies returned deps   windshaft: '
https://registry.npmjs.org/windshaft/-/windshaft-2.5.0.tgz',
50 verbose readDependencies returned deps   yargs: '
https://registry.npmjs.org/yargs/-/yargs-5.0.0.tgz' }
51 silly cache add args [ '[windshaft]', null ]
52 verbose cache add spec [windshaft]
53 silly cache add parsed spec { raw: '[windshaft]',
53 silly cache add   scope: null,
53 silly cache add   name: null,
53 silly cache add   rawSpec: '[windshaft]',
53 silly cache add   spec: '/home/carto/Windshaft-cartodb/[windshaft]',
53 silly cache add   type: 'local' }
54 error addLocal Could not install
/home/carto/Windshaft-cartodb/[windshaft]
55 verbose stack Error: ENOENT, open
'/home/carto/Windshaft-cartodb/[windshaft]'
56 verbose cwd /home/carto/Windshaft-cartodb
57 error Linux 4.1.19-v7+
58 error argv "node" "/home/carto/.nvm/v0.10.26/bin/npm" "install"
"[windshaft]"
59 error node v0.10.26
60 error npm  v2.15.1
61 error path /home/carto/Windshaft-cartodb/[windshaft]
62 error code ENOENT
63 error errno 34
64 error enoent ENOENT, open '/home/carto/Windshaft-cartodb/[windshaft]'
64 error enoent This is most likely not a problem with npm itself
64 error enoent and is related to npm not being able to find a file.
65 verbose exit [ 34, true ]

Do you think that if i resolve dependencies can work?

Thanks nico

2016-10-25 17:59 GMT+02:00 Daniel <notifications@github.com>:
