### ISSUE TITLE
Add `analysis.node_id` to errors for analyses which are invalid due to a cycle

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#584]
We basically need to ensure [this error](https://github.com/CartoDB/camshaft/blob/master/lib/analysis.js#L73) includes a `node_id` in the response. cc: @dgaubert 

---
@jgoizueta commented on [Wed Oct 26 2016](https://github.com/CartoDB/cartodb/issues/10391)

If an analysis is not valid or an error occurs while creating it (prior to registration, execution, etc.) no error appears in the UI. The analysis is left with the progress icon. (we cannot easily generate this situation currently before tampering with the code, so this is not a bug, but please keep reading 😬 )

These are cases in which the map instantiation (GET `.../api/v1/map?config=...`) responds with a 200 and this kind of payload:

``` json
{
  "errors": [
    "Invalid analysis, cycle found"
  ],
  "errors_with_context": [
    {
      "type": "analysis",
      "message": "Invalid analysis, cycle found",
      "analysis": {
        "id": "a1",
        "type": "filter-category"
      }
    }
  ]
}
```

This may seem not very important for the invalid analysis case (because the UI should not allow building an invalid analysis in the first place) but other errors may occur during the analysis creation, and in particular we're working in [pre-checking the analyses](https://github.com/CartoDB/camshaft/issues/209) and this seems like a good way to make them fail if they limits are exceeded.

cc/ @rafatower 

---

@rafatower commented on [Wed Oct 26 2016](https://github.com/CartoDB/cartodb/issues/10391#issuecomment-256370557)

In order of priorities: better to fail silently than starving all resources with a huge analysis. That said, I think Builder is gonna work on improving UI feedback to the user.

---

@xavijam commented on [Mon Oct 31 2016](https://github.com/CartoDB/cartodb/issues/10391#issuecomment-257275611)

cc @alonsogarciapablo and @javierarce 

---

@alonsogarciapablo commented on [Mon Oct 31 2016](https://github.com/CartoDB/cartodb/issues/10391#issuecomment-257310748)

I've tried to replicate what @jgoizueta is describing (manually "breaking" an analysis through the console) and it's working for me. Example, if I add a Filter analysis and I unset the `max` and `min` properties, I get the following response from the maps API when the map is loaded:

```
{
  "errors": [
    "Range filter expect to have at least one value in min or max numeric params"
  ],
  "errors_with_context": [
    {
      "type": "analysis",
      "message": "Range filter expect to have at least one value in min or max numeric params",
      "analysis": {
        "id": "b1",
        "node_id": "b1",
        "type": "filter-range"
      }
    }
  ]
}
```
And, this (beautiful) error is displayed when I re-load the map:

![screen shot 2016-10-31 at 15 38 15](https://cloud.githubusercontent.com/assets/390398/19858014/2ae11a5e-9f80-11e6-943f-b982bc25de22.png)

@jgoizueta comparing this response to the one you posted, I've noticed that there's no `analysis.node_id` in yours, which [is basically what cartodb.js uses](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/error.js#L17) to assign that error to the corresponding analysis node.

@jgoizueta is this happen locally? If so, would you please try this after you upgrade `node-windshaft` to the latest version? thx!

**Comment by dgaubert** [comment]
I'm going to deploy the fix:
<img width="333" alt="screen shot 2016-11-01 at 14 01 03" src="https://cloud.githubusercontent.com/assets/1936888/19923900/daa065d4-a0e9-11e6-93d3-13e3f0c0a051.png">

\o/

**Comment by alonsogarciapablo** [comment]
👍

**Comment by dgaubert** [comment]
Already fixed
