### ISSUE TITLE
add MVT support for named maps z/x/y urls

### ISSUE THREAD

**Issue by javisantana** [CartoDB/Windshaft-cartodb#587]
this kind of urls should work:

https://javi.carto.com/api/v1/map/named/tpl_5e80826a_a5a6_11e6_8df1_0ecd1babdde5/all/0/0/0.mvt

so makes lot of easier to integrate visualizations

**Comment by rochoa** [comment]
If you request only `mapnik` layers, as per https://javi.carto.com/api/v1/map/named/tpl_5e80826a_a5a6_11e6_8df1_0ecd1babdde5/mapnik/0/0/0.mvt, it works.

**Comment by javisantana** [comment]
umh, good to know cc @danicarrion

**Comment by javisantana** [comment]
I guess to have the `all` thing we'd need to give torque support in MVT :party:

**Comment by danicarrion** [comment]
got it, thanks!

**Comment by rochoa** [comment]
I'm closing this one, feel free to open a new one for supporting `all` layers.
