### ISSUE TITLE
Others value is appearing in layer metadata when a value is filtered by a widget

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft-cartodb#600]
## STR

1. Create a map with a layer of the world airports (present in CARTO data library).
2. Style that layer using a fill by value, choose the `type` column. A legend should appear displaying 9 categories (OTHERS should not be visible).
3. Now add a category widget, same column, `type`.
4. Filter the widget by "MAJO" value.
5. Check the new legend generated, OTHERS appears in the list.

**Comment by xavijam** [comment]
cc @rochoa

**Comment by xavijam** [comment]
Sorry if the ticket is not related with this repository. If so, let me know and I'll change it to the proper location 💋 .

**Comment by rochoa** [comment]
Cannot reproduce: https://team.carto.com/u/rochoa/builder/94184ece-be0d-11e6-94e6-0e3ff518bd15.

![screen shot 2016-12-09 at 13 51 57](https://cloud.githubusercontent.com/assets/45346/21049692/b79dd374-be16-11e6-83b7-a9b38847046c.png)

**Comment by xavijam** [comment]
Sorry, it can't happen again due to recent changes over how we set categories in the style.
My apologies :(.
