### ISSUE TITLE
Histogram column type discovery should use original query

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#606]
Histograms try to discover the column type to allow transparent numeric and date columns.

The query to discover the column type uses the filtered query (using the bounding box filter, for instance), in case no data is returned, the column is defaulted to the ::numeric type, and it fails when the column is a date.

**Comment by michellechandra** [comment]
SB: 10821434

This is an urgent issue for an Enterprise client. Is there a potential timeframe for when this bug would be corrected that I can provide the user with?

**Comment by oriolbx** [comment]
Hi ! Are there any updates regarding this issue?
