### ISSUE TITLE
google maps torque tiles

### ISSUE THREAD

**Issue by DinakaranS** [CartoDB/Windshaft-cartodb#619]
Hi,

I am using windshaft for quite a while, its really good.

Now, i want to add a torque layer to google maps. Is it possible to add a torque layer in google maps using windshaft.

Like
new google.maps.ImageMapType({

getTileUrl: function (coord, zoom) {

  return  baseURL + '/' + mapconfig + '/' + token +'/' + zoom + '/' + coord.x + '/' + coord.y + '.png';

},
tileSize: new google.maps.Size(256, 256)
});

**Comment by Algunenano** [comment]
Stale
