### ISSUE TITLE
mvt vector tiles for line features

### ISSUE THREAD

**Issue by DinakaranS** [CartoDB/Windshaft-cartodb#620]
Hello, i'm using the mvt endpoint to serve out vector tiles --> its working great for points and polygons, however with Line Features --> i get this erroneous image (has extra flickering lines)

I am using mapbox-gl.js v0.31.0

Are you familiar with this issue?

![flickering](https://cloud.githubusercontent.com/assets/8424594/22242632/140807fe-e24a-11e6-9332-5f90525aad0d.png)

**Comment by chriswhong** [comment]
![maputnik_and_cwhong___carto](https://cloud.githubusercontent.com/assets/1833820/22915654/c16ef694-f246-11e6-8d20-cca6cd86b61c.png)

+1, I am seeing these bizarre horizontal and vertical lines when displaying linestrings in mapboxGL from carto-generated MVTs.

**Comment by almccon** [comment]
Same.
<img width="941" alt="screen shot 2017-05-04 at 4 may 1 08 34" src="https://cloud.githubusercontent.com/assets/1212178/25722946/d810bce4-30ca-11e7-8f4c-9d15012bf7de.png">
<img width="832" alt="screen shot 2017-05-04 at 4 may 1 06 04" src="https://cloud.githubusercontent.com/assets/1212178/25722947/d814c58c-30ca-11e7-8ce7-fdfdd0336e3e.png">

**Comment by donflopez** [comment]
I think it could be because of buffer-size property, can you try to change [this config property](https://github.com/CartoDB/Windshaft-cartodb/blob/master/config/environments/development.js.example#L151) to 0?

**Comment by almccon** [comment]
@donflopez where would I change that? I'm using .mvt from CARTO.com, following the example here: http://bl.ocks.org/rochoa/eca69273cd2b6cf86673

**Comment by donflopez** [comment]
Ohhh, we're fixing that in production, but you have to wait. I thought that you were using this project directly, if you use this in local you can go to `665-buffer-size` branch and make what I said, If not you have to wait for [this PR](https://github.com/CartoDB/Windshaft-cartodb/pull/673) that fix it.

**Comment by dgaubert** [comment]
https://github.com/CartoDB/Windshaft-cartodb/pull/673 was merged time ago. Closing this issue, reopen if needed.
