### ISSUE TITLE
Error when aggregation dataviews are required for tables with overviews and aggr op is avg/min/max

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#625]
For each dataview class in https://github.com/CartoDB/Windshaft-cartodb/tree/master/lib/cartodb/models/dataview
we have a corresponding subclass in https://github.com/CartoDB/Windshaft-cartodb/tree/master/lib/cartodb/models/dataview/overviews
that handle the case that overviews a available for the query.

We have an inconsistency between the aggregation dataview with and without overviews, because the latter does not support avg, min or max operations (only count, sum).

This is because when overviews/aggregation was implemented the base aggregation only supported count and sum; when the other operations were [added later](https://github.com/CartoDB/Windshaft-cartodb/commit/e8df09c85b70c61aae6bfe126738f22647945f3f) we didn't update the overviews subclass accordingly.

This causes an error in the Builder UI if we used an aggregation widget on a table with overviews and change the operation to avg, min or max.

```javascript
{"errors":["Property 'avg' of object #<Object> is not a function"],"errors_with_context":[{"type":"property_not_function","message":"Property 'avg' of object #<Object> is not a function"}]}
```

To fix this we can add support for  `avg` in https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/dataview/overviews/aggregation.js (which can be done "exactly" for numerical columns) and we can fallback to non-overviews for min/max.

**Comment by jsanz** [comment]
cc. @CartoDB/support for awareness This applies (using BUILDER terminology) when you have a category widget and you want to set up a different aggregation method than `COUNT` or `SUM` for layers with Overviews.

**Comment by Algunenano** [comment]
Stale. This also used to crash the process, but this was fixed in https://github.com/CartoDB/Windshaft-cartodb/pull/1139
