### ISSUE TITLE
Category "OTHER" is not calculated using the selected agg function

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#628]
When a category widget displays data aggregated by any functio, the OTHER category still sums the values of the not displayed categories. 

Graphically (aggregating by **AVG(my_column)**):

![image](https://cloud.githubusercontent.com/assets/9017165/23159659/ed5cb092-f823-11e6-9722-dba344c59eee.png)

The expected result should be that the OTHER value should be calculated using the very same aggregating function the widget is using.

In the example above, OTHER should display the average value of the categories not shown in the TOP5, instead of summing? counting? the leftovers

---

Server response:

![image](https://cloud.githubusercontent.com/assets/9017165/23172899/b0eabe90-f857-11e6-90e1-8a47111a2ac4.png)

This supersedes https://github.com/CartoDB/cartodb/issues/11590.

**Comment by ethervoid** [comment]
## Acceptance

1. Create an empty dataset
2. Add this query to make the base of data for the test:
    ```
   WITH data as ( 
        select generate_series(1,3) as val, 'other_a' as cat, ST_SetSRID(ST_MakePoint(0,0),4326) as the_geom, ST_Transform(ST_SetSRID(ST_MakePoint(0,0),4326),3857) as the_geom_webmercator
        UNION ALL
        select generate_series(4,6) as val, 'other_b' as cat, ST_SetSRID(ST_MakePoint(0,0),4326) as the_geom, ST_Transform(ST_SetSRID(ST_MakePoint(0,0),4326),3857) as the_geom_webmercator
        UNION ALL
        select generate_series(7,9) as val, 'other_c' as cat, ST_SetSRID(ST_MakePoint(0,0),4326) as the_geom, ST_Transform(ST_SetSRID(ST_MakePoint(0,0),4326),3857) as the_geom_webmercator
        UNION ALL
        select generate_series(10,12) as val, md5(generate_series(0,4)::text) as cat, ST_SetSRID(ST_MakePoint(0,0),4326) as the_geom, ST_Transform(ST_SetSRID(ST_MakePoint(0,0),4326),3857) as the_geom_webmercator
    )
    SELECT row_number() OVER (ORDER BY val asc) as cartodb_id, val, cat, the_geom, the_geom_webmercator FROM data
    ```
3. Create a map using the `Create Map` button in the table view
3. Create a new category widget using the cat column and:
    - [ ] Check COUNT operation returns `9`
    - [ ] Check SUM operation returns `45`
    - [ ] Check AVG operation returns `5`
    - [ ] Check MAX operation returns `9`
    - [ ] Check MIN operation returns `1`

**Comment by rochoa** [comment]
Everything looks OK. :shipit:.

**Comment by ethervoid** [comment]
Thank you very much :)

**Comment by rochoa** [comment]
😢  I just realised that I totally forgot about overviews implementation, which has the same problem.

cc @jgoizueta I start to feel we need to rethink the approach we use for overviews, as this is not the first time we miss to fix something in both places. 

OTOH, I would not stop releasing the fix, but I would open another one for the overviews instance of the problem.

**Comment by ethervoid** [comment]
:O :(

Totally my bad, I looked into it when I was learning about it but I totally forgot to change it :_(

Opening a new issue to fix the overviews part.

**Comment by ethervoid** [comment]
Using the issue for the overviews part too
