### ISSUE TITLE
Widgets in named-maps

### ISSUE THREAD

**Issue by dmed256** [CartoDB/Windshaft-cartodb#677]
For the Python API, we want to add widgets for named-maps. There is currently no way to do so or not in the supported API.

For example, being able to template the `widgets` section in the deep-insights example
- https://github.com/CartoDB/deep-insights.js/blob/master/examples/dynamic_widgets.html
- https://editor3.carto.com/api/v3/viz/94a4362c-491f-11e6-a764-0e233c30368f/viz.json

**Comment by Algunenano** [comment]
Stale
