### ISSUE TITLE
Bbox filters split 180-meridian-crossing boxes incorrectly

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#694]
This demonstrates and fixes it: https://github.com/CartoDB/Windshaft-cartodb/commit/26c5bfb0e38630b84df4426f5182df5271965d18

Note a longitude range 90, 190 would be split into 90,180 and -180,10 while the latter should be -180,-170.

cc/ @rochoa

**Comment by rochoa** [comment]
Nice catch! 😄 

I cherry-picked it and created a PR.
