### ISSUE TITLE
Avoid name clashing in widget queries

### ISSUE THREAD

**Issue by rafatower** [CartoDB/Windshaft-cartodb#707]
We've had some issues with widget queries because of collision of identifiers in our queries with column names in user tables.

For example, this [query](https://github.com/CartoDB/Windshaft-cartodb/blob/49f5b0b480cf7a63d3b423209758af69a61387af/lib/cartodb/models/dataview/aggregation.js#L81-L88) for aggregation fails if the user applies it to a source table with a column named `category`, with the following error:

```
ERROR:  column "_cdb_aggregation_all.institutions" must appear in the GROUP BY clause or be used in an aggregate function
LINE 46: SELECT CAST(institutions AS text) AS category, count(institu...
                     ^
```

Generating unique identifiers from windshaft-cartodb can be hard. It may involve extra queries to know about the structure of the db and/or parsing queries.

As a cost effective solution to this problem, I propose to use a prefix to those identifiers with something, so that, for instance, `category` becomes `_widget_category` (unlikely to clash with a column name), and replace proactively all those in our code.

**Comment by rafatower** [comment]
Meanwhile the workaround is to tell the user to rename the column if the problem arises.

**Comment by Algunenano** [comment]
Stale.
