### ISSUE TITLE
[vector] Empty mvt tiles are being answered like 404

### ISSUE THREAD

**Issue by xavijam** [CartoDB/Windshaft-cartodb#709]
## STR
- Create a map of points (less than 500k).
- Publish it
- Go to the public map.
- Move the map and go to a placer where there are not features.
- Check browser console and see that 404 errors are appearing.

cc @dgaubert

**Comment by javisantana** [comment]
I think this is the right thing (maybe it should be a 204 - no content) because those tiles are the one that have no data therefore it raises a 404 not found

**Comment by xavijam** [comment]
204 no content 👍

**Comment by dgaubert** [comment]
4xx error means that the client did something wrong and that isn't the case. From my point of view 204 fits much better. When raster we send 200 and empty tile.

**Comment by dgaubert** [comment]
Fixed: https://github.com/CartoDB/Windshaft-cartodb/releases/tag/3.9.7

**Comment by dgaubert** [comment]
Fixed in production
