### ISSUE TITLE
Analysis runs twice when editing in builder UI

### ISSUE THREAD

**Issue by javitonino** [CartoDB/Windshaft-cartodb#716]
STR
1. Create a new map
2. Add a DO multiple-measure analysis and run it
3. Write down the number of DO used credits you have
4. Edit the DO analysis (e.g: change the measure you are requesting) and run it again
5. Look at the number of used DO queries. It has used up double the credits it should!

This only happening when editing an existing analysis, not when creating a new one. What happens under the hood is that Builder is sending two map instantiation requests in parallel (with the exact same analysis tree). It looks like there is some race condition in Windshaft that makes the analysis run twice in this case. So it takes longer to finish, and consumes double the credits.

I was able to reproduce it using a curl script, something like:
```
curl 'http://worg1.localhost.lan:8181/api/v1/map?config=[...] &
curl 'http://worg1.localhost.lan:8181/api/v1/map?config=[...] &
```
The `&` is key. If you remove it the script waits for the response from one request before sending the next, and that avoids the problem.

Not sure if this should be fixed Builder side (send only one request) or Windshaft side (run the analysis only once). I'll let you guys decide @rochoa @xavijam

**Comment by ramiroaznar** [comment]
Can we close this?

**Comment by javitonino** [comment]
Still an issue. We have both the double instantiation from builder, and the double execution from windshaft. The good thing is that DO credits are now unlimited, but double execution is still concerning.

**Comment by Algunenano** [comment]
Stale
