### ISSUE TITLE
API returns unnecessary empty buckets in histogram dataviews

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft-cartodb#732]
After changes because of https://github.com/CartoDB/cartodb/issues/12618#issuecomment-323688949 now we send `start` and `end` values to retrieve totals of a histogram dataview.

Sometimes, depending of the limits, the API answer with an empty bucket at the end.

![toggle](https://user-images.githubusercontent.com/1078228/29617518-76dc8262-8815-11e7-8ebc-e174b5ceabb2.gif)

This is an issue both for Windshaft and Builder to know the best way to calculate / send limits depending on the aggregation and timezones.

**Comment by dgaubert** [comment]
Hey @ivanmalagon!

I think this was fixed time ago, wasn't it?

**Comment by ivanmalagon** [comment]
We can't wait one month and close it on its first birthday. 😝 

I don't remember exactly the details but I'm not aware of any recent ticket / issue / support about this. I'll close it.
