### ISSUE TITLE
Conflict routes 

### ISSUE THREAD

**Issue by oleurud** [CartoDB/Windshaft-cartodb#759]
We have a conflict between this routes and sometimes we have unexpected behavior:
- '/:token/:layer/:z/:x/:y.(:format)' (layergroup.js)
- '/static/named/:template_id/:width/:height.:format' (named_maps.js)

Now, we have a middleware validating if the matched route is not correct. We should skip this controller when the path does not match the token pattern through regular expressions or another solution.

**Some interesting links**
- https://expressjs.com/en/guide/routing.html
- https://www.npmjs.com/package/path-to-regexp
- http://forbeslindesay.github.io/express-route-tester/

**And more info**
https://github.com/CartoDB/Windshaft-cartodb/pull/751#issuecomment-332196551

**Comment by dgaubert** [comment]
It was fixed [here](https://github.com/CartoDB/Windshaft-cartodb/commit/56495522b8a23d96db22789dd654ec6d032ee3d1)
