### ISSUE TITLE
review node|express security modules/best practices

### ISSUE THREAD

**Issue by enekid** [CartoDB/Windshaft-cartodb#761]
- [ ] official  express.js [cors middleware](https://www.npmjs.com/package/cors)
- [ ] [helmet](https://www.npmjs.com/package/helmet)
- [x] [nsp](https://www.npmjs.com/package/nsp)

More recommendations can be found in the [express documentation](https://expressjs.com/en/advanced/best-practice-security.html)

**Comment by Algunenano** [comment]
Stale
