### ISSUE TITLE
Changes to dataviews and filters

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft-cartodb#776]
As we continue the development of `cartodb.js v4` we realized that we need some changes on dataviews and filters.

Until now, dataviews acted as a proxy to filters. We want to split this, having filters and dataview separated to reflect better the underlying architecture of the system.

There is an ongoing PR on https://github.com/CartoDB/Windshaft-cartodb/compare/analyses-filters that enables to send the filter parameters attached to analysis nodes instead of dataviews.

#### Problem 1: own_filter

The problem is that because of these last changes, calling the dataview URL with `own_filter` has stopped working. It's time to rethink the endpoint.

After some research, we need three ways of calling a dataview endpoint:

1. Fetch data from analysis/source with No filters applied. 

2. Fetch data from analysis/source with All filters applied.

3. Fetch data from analysis/source with All filters except the one applied to the same analysis and column.

Number 3 is not working now. Prior to this, the filters had the same id as the dataview so it was easy to relate them. Now it seems that this link is broken. Debugging https://github.com/CartoDB/Windshaft-cartodb/blob/73a633ae7d19cdcfae1e45e20090483e37251e07/lib/cartodb/models/mapconfig/adapter/analysis-mapconfig-adapter.js#L142 we can see that now with last changes, `own_filter_on` and `own_filter_off` return the same query.

![image](https://user-images.githubusercontent.com/1078228/31660569-175f4e66-b338-11e7-9bc4-386a812cf2db.png)

So, we need:

- A parameter to specify what data we want to retrieve. It could be `filters` with 3 possible values:
    - `?filters=none`: no filters applied.
    - `?filters=all`: all filters applied.
    - `?filters=others`: all filters except the one applied to the same analysis and column. Default.

#### Problem 2: category search

In category dataview URL there is another options that it's used to search categories.

```
dataviewUrl/search?q=text
```

With the last changes, that search has stopped working since it's affected by any filter applied to the same analysis and column.

We need that endpoint to search in all categories with no filters applied.

**Comment by alonsogarciapablo** [comment]
> ?filters=others: all filters except the one applied to the same analysis and column.

We have to take into account that multiple filters can be applied to the same analysis and column at the same time.

**Comment by ivanmalagon** [comment]
There's an ongoing work in branch https://github.com/CartoDB/Windshaft-cartodb/tree/analyses-filters-params

@dgaubert Two things:
- Can you modify `own_filter=-1` to `nofilters=true` to get a more syntactic param?
- Leveraging that the Pisuerga flows through Valladolid... can you return `bin_end` in numeric histograms to avoid rounding errors? (you know what I'm talking about)

Thanks!

**Comment by ivanmalagon** [comment]
Semishipped 🚀 

`no_filters` is deployed and working properly but it's only used in histograms.

Regarding problem 2 (search categories) I'll open a ticket for it after doing further research.
