### ISSUE TITLE
Return custom mvt when limits are reached

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/Windshaft-cartodb#782]
We need to return a custom mvt with a `429` status code when limits are reached. 

Design issue: #TBD

**Comment by dv343** [comment]
This requires to
 - Pre-generate an error MVT tile with the orange stripped square
 - Return that static tile on error

**Comment by oleurud** [comment]
Development finished and working on staging

**Comment by dv343** [comment]
Isn't this done already?

**Comment by oleurud** [comment]
It is not in production. Maybe you will need to wait until Monday

**Comment by rubenmoya** [comment]
We will start merging things tomorrow! I'll keep you posted!

**Comment by rubenmoya** [comment]
Closed via https://github.com/CartoDB/Windshaft-cartodb/pull/787
