### ISSUE TITLE
Add number of categories param to Categories dataview

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft-cartodb#786]
As of now, category dataview only returns 5 categories + 1 others category. This is hardcoded in Windshaft.

In order to make the category dataview more useful to the final users in the `cartodb.js v4` releases, it'd be great to have the options of asking for a certain number of categories. 6 categories is a number that makes sense in our widget implementation but no for a general use case.

Proposal: use a query param to set it.

**Comment by dgaubert** [comment]
Done #788
