### ISSUE TITLE
Test helper for comparing vector tiles

### ISSUE THREAD

**Issue by oleurud** [CartoDB/Windshaft-cartodb#794]
We have a test helper to [compare raster tiles](https://github.com/CartoDB/Windshaft-cartodb/blob/master/test/support/assert.js#L14-L38) but we have not for vector tiles and it will be useful to have it.

We started talking about in [this PR](https://github.com/CartoDB/Windshaft-cartodb/pull/787#discussion_r151085784).

@dgaubert @dv343 @enekid

**Comment by dgaubert** [comment]
I think we are fine using this approach:
```
testClient.getTile(0, 0, 0, { format: 'mvt' }, (err, res, mvt) => {
    const expected = [
        {
            type: 'Feature',
            id: 1,
            geometry: { type: 'Point', coordinates: [0, 0] },
            properties: { ... }
        },
        {
            type: 'Feature',
            id: 2,
            geometry: { type: 'Point', coordinates: [0, 0] },
            properties: { ... }
        }
    ];

    const actual = JSON.parse(mvt.toGeoJSONSync(0)).features;

    assert.deepEqual(actual, expected);
    done();
});
```
