### ISSUE TITLE
Allow MVT tiles without CartoCSS

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#802]
In order to make requesting MVT tiles more developer-friendly, we need to remove the hard requirement on `options.cartocss[_version]`.

Let's start with a simple approach, when:
 1. All `cartodb` layers have the `cartocss` option: allow to request PNG and MVT tiles.
 1. All `cartodb` layers miss `cartocss` option: it's only possible to request MVT tiles; when requesting PNG tiles, we return an error.
 1. The `cartodb` layers mix `cartocss` with no `cartocss` option: we return an error at instantiation.

**Comment by dgaubert** [comment]
Related PR:
 - https://github.com/CartoDB/Windshaft-cartodb/pull/803
 - https://github.com/CartoDB/Windshaft/pull/575
 - https://github.com/CartoDB/grainstore/pull/139

**Comment by dgaubert** [comment]
Ready for CR

**Comment by rochoa** [comment]
This is already done.
