### ISSUE TITLE
Tilejson and url templates with api_keys

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#842]
The urls the the tilejson and url templates of map instantiation metadata do not included an api_key if it's provided for instantiation. 

So it is not possible to use tilejson/urls directly when tiles are going to be retrieved with an api_key (e.g. for having greater limits).

We could include the api_key in the urls whenever the instantiatioin has an api_key. Am I missing some use case where the user wants to use the api_key for map instantiation but not for fetching the tiles?

**Comment by oleurud** [comment]
PR #983

**Comment by oleurud** [comment]
Merged and deployed
