### ISSUE TITLE
Configurable MVT extent

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/Windshaft-cartodb#843]
Right now the MVT extent is a global tiler configurable flag. It would be interesting to let it be changed at map instantiation time for two reasons:

- Allow to fine tune the value. Lower values can be used to improve the tile size at the cost of lower quality over-zooming. The current value is very conservative (i.e. it prefers high quality overzooming over tile size). This is probably a good default, but it is useful to change it depending on the actual usage.
- Allow for "Just One Tile" optimization. This optimization would be to download the entire map just once. This can only work fine with vector tiles, with a very large extent (close or equals to the MVT maximum extent) and with not very large datasets (i.e. it doesn't make sense to download an entire world basemap). However this optimization would be extremely useful for small and medium sized datasets since the map could be loaded with just one request (which would be very cache friendly).

Implementation notes:
Windshaft doesn't need to be changed: https://github.com/CartoDB/Windshaft/blob/620bb20bf011d42bf211469affc9b435ff28393b/lib/windshaft/renderers/pg-mvt/renderer.js#L29

CC: @jgoizueta @rafatower @rochoa @dgaubert

**Comment by jaakla** [comment]
For "just one tile" case the geobuf (https://github.com/mapbox/geobuf) might be worth to checked, even it is much less well known and implemented.

**Comment by davidmanzanares** [comment]
@Algunenano What is the status of this? Is already deployed in production?

**Comment by Algunenano** [comment]
This is now merged and released. Please let me know if you find any issue.
