### ISSUE TITLE
`point-grid` aggregation not working.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft-cartodb#846]
Example at http://bl.ocks.org/ivanmalagon/raw/990ddddf35aa456a285e6cffa668dce2/ (open devtools to see the error in the first error trace).

![image](https://user-images.githubusercontent.com/1078228/34952533-5bc63e42-fa1a-11e7-8cda-3fbb346e977b.png)

Windshaft returns `Postgis Plugin: ERROR:  column "cartodb_id" does not exist` when selecting `point-grid` aggregation. If we choose `centroid` or `point-sample` it works flawlessly with the very same example.

**Comment by jgoizueta** [comment]
Fixing this in PR #855
