### ISSUE TITLE
Unify staging and production logs 

### ISSUE THREAD

**Issue by oleurud** [CartoDB/Windshaft-cartodb#852]
The production is working well, staging don't.

**Comment by dgaubert** [comment]
@oleurud, shall we close this issue?

**Comment by oleurud** [comment]
No. Sorry I should add more info.

This was the alert: https://github.com/CartoDB/cartodb-platform/issues/3847#issuecomment-358948845

We have different format/structure for the logs of staging and production, and as a result, `our regexp matches only the production format`

**Comment by Algunenano** [comment]
It's currently the same
