### ISSUE TITLE
Remove old authorization system

### ISSUE THREAD

**Issue by dgaubert** [CartoDB/Windshaft-cartodb#881]
After the redis `api-keys` migration, we can deprecate old authorization system and remove the code related to keeping the old behavior (use public user credentials when no `api-key` or an invalid one is provided in the request).

**Comment by dgaubert** [comment]
Before proceeding:
1. check new users are created with new Auth API keys (check it with @CartoDB/backend)
2. Keep the behavior: the absence of API key or a wrong one in the request means that is authenticated as `default_public` (to no break CARTO.js examples)

**Comment by inigomedina** [comment]
Ready to be closed?

**Comment by dgaubert** [comment]
Still in development. We will close it when it's deployed
