### ISSUE TITLE
Sending "placement" value in aggregation options triggers an error

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/Windshaft-cartodb#924]
By default, when sending aggregation options, we can send a placement value which, by default, it is supposed to be equal to `point-sample`. If we do not send the `placement` option, Windshaft does not trigger any error [1] . However, when sending this value set to `"point-sample"`, we see an error [2].

[1]
```js
var DEFAULT_AGGREGATION = {
  threshold: 100000,
  resolution: 1
};
```
![captura de pantalla 2018-04-02 a las 16 49 59](https://user-images.githubusercontent.com/3824953/38201394-72eaf8e6-3698-11e8-845c-6a9a9562d636.png)

[2]

```js
var DEFAULT_AGGREGATION = {
  threshold: 100000,
  resolution: 1,
  placement: 'point-sample'
};
```

![captura de pantalla 2018-04-02 a las 17 04 04](https://user-images.githubusercontent.com/3824953/38201262-f44d59de-3697-11e8-97d6-fc1db9fcc8f0.png)

**Comment by jgoizueta** [comment]
It's probably fixed by some of the fixes [in this PR](https://github.com/CartoDB/Windshaft-cartodb/pull/913) that's already in master.

Could you check if the versio of the tiler in master fixes the problem?

**Comment by elenatorro** [comment]
Thanks, @jgoizueta! I will check it as soon as I can :)

**Comment by dgaubert** [comment]
@elenatorro is that already fixed??

**Comment by dgaubert** [comment]
ping @elenatorro ^^

**Comment by dgaubert** [comment]
Closing, reopen if needed.
