### ISSUE TITLE
Different legends when Default Point aggregation is enabled in Builder

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#935]
Hello! @elenatorro tried to enable Default Point Aggregation in Builder (in https://github.com/CartoDB/cartodb/pull/13718) and we discovered a couple of differences in the maps when default point aggregation is and isn't enabled:

**1. Values in legends are different**

No aggregation:

<img width="456" alt="screen shot 2018-04-10 at 14 38 39" src="https://user-images.githubusercontent.com/390398/38557371-23e8ac08-3ccd-11e8-9266-69dbbfa58923.png">

Default Point Aggregation enabled:

<img width="364" alt="screen shot 2018-04-10 at 14 38 44" src="https://user-images.githubusercontent.com/390398/38557363-1cb04a2c-3ccd-11e8-98dd-993a1a23cdc1.png">

~**2. Points are different**~

~No aggregation:~

![screen shot 2018-04-09 at 14 13 13](https://user-images.githubusercontent.com/390398/38557380-2d201b30-3ccd-11e8-8e59-505bb37bcca1.png)
 
~Default Point Aggregation enabled (for some reason there are more points!!!):~

![screen shot 2018-04-09 at 14 13 28](https://user-images.githubusercontent.com/390398/38557386-31f88822-3ccd-11e8-87b1-53266f4492b4.png)

---

@dgaubert @jgoizueta we need your help here. We were expecting Default Point Aggregation to be transparent for Builder users but it's clearly not the case right now. Could you 🙏 give us some more context about these two issues?

- Why are the values in the legends different? Shouldn't we be using the original query for the legends?
- Why are we seeing different points in both cases?

Thanks a lot for your help! ❤️

**Comment by dgaubert** [comment]
Could you share the map?

**Comment by alonsogarciapablo** [comment]
@elenatorro could you please attach the map you used [here](https://github.com/CartoDB/cartodb/pull/13718#issuecomment-377921874)? Thanks!

**Comment by jgoizueta** [comment]
The default aggregation is a spatial sample of the original. And the cartodb_id is sampled too, so the variation shown in the image above is reasonable.

**Comment by jgoizueta** [comment]
But the disappearing points must be a bug: default aggregation is to pixel level, so no visible features should go away

**Comment by jgoizueta** [comment]
Hey wait! it's not disappearing points, but appearing points! 😕

**Comment by alonsogarciapablo** [comment]
> Hey wait! it's not disappearing points, but appearing points! 😕

Yes, that's the weird thing!

**Comment by alonsogarciapablo** [comment]
The dataset that @elenatorro used can be obtained using the following URL:

https://cdbsol-admin.carto.com/api/v2/sql?q=SELECT+*+FROM+gecat_geodata+LIMIT+150000&format=geojson&filename=gecat_geodata

I did some quick tests with CARTO.js and I could only see some differences in the ramp colors and map metadata, but points were exactly the same. Let's forget about that then.

**No aggregation:**

![image](https://user-images.githubusercontent.com/390398/38611954-8203f5c8-3d85-11e8-9fa7-525180645a4a.png)

Metadata rules:

```
{
  "rules": [
    {
      "selector": "#layer",
      "prop": "marker-fill",
      "column": "speed",
      "mapping": ">",
      "buckets": [
        {
          "filter": {
            "type": "range",
            "start": 0,
            "end": 0.9
          },
          "value": "#ffc6c4"
        },
        {
          "filter": {
            "type": "range",
            "start": 0.9,
            "end": 4.8
          },
          "value": "#ee919b"
        },
        {
          "filter": {
            "type": "range",
            "start": 4.8,
            "end": 21.1
          },
          "value": "#cc607d"
        },
        {
          "filter": {
            "type": "range",
            "start": 21.1,
            "end": 65.6
          },
          "value": "#9e3963"
        },
        {
          "filter": {
            "type": "range",
            "start": 65.6,
            "end": 254.8
          },
          "value": "#672044"
        }
      ],
      "stats": {
        "filter_avg": 30.0642533333344
      }
    }
  ]
}
```

**Default point aggregation:**

![image](https://user-images.githubusercontent.com/390398/38611975-8f9a47dc-3d85-11e8-833d-d15c73acb292.png)

Metadata rules:

```
{
  "rules": [
    {
      "selector": "#layer",
      "prop": "marker-fill",
      "column": "speed",
      "mapping": ">",
      "buckets": [
        {
          "filter": {
            "type": "range",
            "start": 0,
            "end": 1.2
          },
          "value": "#ffc6c4"
        },
        {
          "filter": {
            "type": "range",
            "start": 1.2,
            "end": 10.3
          },
          "value": "#ee919b"
        },
        {
          "filter": {
            "type": "range",
            "start": 10.3,
            "end": 57.7
          },
          "value": "#cc607d"
        },
        {
          "filter": {
            "type": "range",
            "start": 57.7,
            "end": 114.4
          },
          "value": "#9e3963"
        },
        {
          "filter": {
            "type": "range",
            "start": 114.4,
            "end": 170.1
          },
          "value": "#672044"
        }
      ],
      "stats": {
        "filter_avg": 51.1102564102564
      }
    }
  ]
}
```

@dgaubert Differences in the color ramp metadata... feature or bug?

**Comment by dgaubert** [comment]
> I did some quick tests with CARTO.js and I could only see some differences in the ramp colors and map metadata, but points were exactly the same. Let's forget about that then.

Yep, that's why I wanted to check it by myself, it was related to a regression that I introduced last week. As you can see, it's already fixed.

> Differences in the color ramp metadata... feature or bug?

Neither of the two. That's expected if you aggregate by `point-sample` you are getting just one point (the one with lower `cartodb_id`) for the entire grid (pixel usually) so the column that you choose to perform the ramp has fewer data so obviously the buckets calculated are different because the data is different.

And this is the crux of the matter, the buckets have to be calculated based on the data that you are actually seeing. If we calculate buckets based on the original data you will end up having points rendered with different color or size that has to be rendered.

From my point of view: we cannot use aggregation in a transparent way. The user must apply aggregation explicitly because I can't see a way to apply aggregation w/o having differences between both versions of the map.

**Comment by alonsogarciapablo** [comment]
Thanks @dgaubert!

> And this is the crux of the matter, the buckets have to be calculated based on the data that you are actually seeing. If we calculate buckets based on the original data you will end up having points rendered with different color or size that has to be rendered.

Yes, you're totally right. Both the colors in the map and the colors (and values) in the metadata that we use for the legends have to match.
