### ISSUE TITLE
Grid.json not returned date fields

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/Windshaft-cartodb#946]
### Context

When setting interactivity in a layer requiring a date column, the grid.json tiles return `null` as the value of that column.

`grid.json`

Here you can see it's returning `null` as `last_review` for feature with `cartodb_id` 5606.

![image](https://user-images.githubusercontent.com/1078228/39367277-9167d1c0-4a36-11e8-9e3b-1df710c5b429.png)

`Selecting that feature via SQL`

![image](https://user-images.githubusercontent.com/1078228/39367312-a8d7f646-4a36-11e8-8a7e-f0939378b01c.png)

![image](https://user-images.githubusercontent.com/1078228/39367321-af18fe56-4a36-11e8-8156-5111acedb314.png)

You can use this dataset to check it.

[airbnb listings.csv.zip](https://github.com/CartoDB/Windshaft-cartodb/files/1955428/airbnb.listings.csv.zip)

**Comment by ramiroaznar** [comment]
@dgaubert `won't fix` right?

**Comment by dgaubert** [comment]
I'd say yes. In this repository at least.
