### ISSUE TITLE
Document named maps and static maps into the reference

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/Windshaft-cartodb#975]
We currently have documentation about the Maps API reference here: https://carto.com/developers/maps-api/reference/. Part of the documentation should be in there is being exposed as guides content:

- Named Maps: https://carto.com/developers/maps-api/guides/named-maps/
- Static Maps: https://carto.com/developers/maps-api/guides/static-maps-API/

In the reference, we don't provide any documentation

![screenshot-carto com-2018 06 11-13-44-40](https://user-images.githubusercontent.com/856319/41229809-aa7e9bc0-6d7d-11e8-96a8-6751685d48f1.png)

So, we should document those endpoints, so that the contents are displayed under the reference path.

cc/ @luisbosque @ramiroaznar

**Comment by inigomedina** [comment]
Is this issue in progress?

**Comment by dgaubert** [comment]
Is in TODO, do you need it ASAP?

**Comment by inigomedina** [comment]
Sorry, I assumed that it was assigned to be done in the RT.

I do not need ASAP. I just wanted to check its status. Thanks, man.

**Comment by ramiroaznar** [comment]
Let me know if you need this to be added again to the RT kanban.

**Comment by inigomedina** [comment]
Yes, we need that, @ramiroaznar.

**Comment by ramiroaznar** [comment]
Don't know why this was moved out of the RT flow, @jgoizueta will take care of this next turn.

**Comment by inigomedina** [comment]
Nice, @ramiroaznar.

@jgoizueta, here to help. If you need context, information, or any other thing that can help you to understand how we are currently documenting other similar APIs, just whisper. 😃

**Comment by dgaubert** [comment]
PR: https://github.com/CartoDB/Windshaft-cartodb/pull/1023

Ready for CR

**Comment by dgaubert** [comment]
You can check it here: ttp://test-mapsapi-975.developers.carto-staging.com/developers/maps-api/reference/#tag/Named-Maps

**Comment by dgaubert** [comment]
Done
