### ISSUE TITLE
Preaggregation filters

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/Windshaft-cartodb#978]
We need a way to define per layer filters when instantiating a map. For efficiency we need the Maps API to do this at map instantiations so that:
* The filters can be applied to the data used in tiles
* The filters are not applied for fetching metadata stats
* The filters are only applied to sufficiently large datasets

Filters can be supplied per layer, parameterised (rather than in SQL syntax), with a threshold option so that they will be applied only if the estimated number of rows is larger than the threshold. These filters will be applied to the layer query (wrapping it with a WHERE clause) so that they apply before any aggregation. The layer metadata stats that we already have will be computed without the filters applied. The instantiation metadata will include a flag per layer to indicate if filters have been applied.

We should also add a filter_threshold parameter to the layer aggregation options, so that the post-aggregation filters can also be conditionally applied (on the size of the data).

Example MapConfig with a filter `price BETWEEN 10 AND 100 AND category='house'` applied when more than 500k rows:

```javascript
{
    layers: [
        {            
            type: 'cartodb',
            options: {
                sql: 'SELECT * FROM dataset',
                filter_threshold: 500000,
                filter: {
                    type: 'and',
                    left: {
                        type: 'between',
                        column: 'price',
                        low_value: 10,
                        high_value: 100
                    },
                    right: {
                        type: 'equal',
                        column: 'category',
                        value: 'house'
                    }
                }
            }
        }
    ]
}
```

Example: aggregation filters only to datasets over 500K rows

```
{
    layers: [
        {            
            type: 'cartodb',
            options: {
                sql: 'SELECT * FROM dataset',
                aggregation: {
                    threshold: 1,
                    filter_threshold: 500000,
                    columns: {
                        value: { aggregate_function: 'sum', aggregated_column: 'value' }
                    },
                    filters: {
                        value: { greater_than: 100 }
                    }
                }
            }
        }
    ]
}
```

We won't support general SQL expressions, the filter nodes that we should support are:

* AND (with two arbitrary expressions, i.e. nodes)
* OR (with two arbitrary expressions, i.e. nodes)
* IN (column IN list_of_values)
* NOT IN (column NOT IN list of values)
* BETWEEN (column BETWEEN lower_value AND upper_value)
* EQUALS (column = value)
* NOT EQUALS (column != value)
* IS LESS THAN (column < value)
* IS GREATER THAN (column > value)
* IS LESS THAN OR EQUAL TO(column <= value)
* IS GREATER THAN OR EQUAL TO (column >= value)

The SQL-generation logic can be taken from CARTO VL where it is already implemented in `windshaft-filtering.js`

**Comment by Algunenano** [comment]
Already implemented
