### ISSUE TITLE
assume content-type 'application/json' as default

### ISSUE THREAD

**Issue by strk** [CartoDB/Windshaft-cartodb#99]
See https://github.com/CartoDB/Windshaft/issues/95

**Comment by dgaubert** [comment]
we can consider this issue as implemented as every endpoint uses `send-response` or `error` middlewares which internally responds with [`res.json`](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/api/middlewares/send-response.js#L15) when the response is a `json` and [`res.send`](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/api/middlewares/send-response.js#L8) when the response is a `buffer`. 

Note: Express internally sets correct `content-type`. See: http://expressjs.com/en/4x/api.html#res.json
