### ISSUE TITLE
Brittle test for MVT metadata (test or feature bug?)

### ISSUE THREAD

**Issue by rafatower** [CartoDB/Windshaft-cartodb#993]
I noticed this test fails in local:

```
$ ./run_tests.sh test/acceptance/layergroup-metadata.js
[...]
Running tests


  layergroup metadata
    1) tiles base urls with api key: 1234
    2) "after each" hook for "tiles base urls with api key: 1234"


  0 passing (648ms)
  2 failing

  1) layergroup metadata tiles base urls with api key: 1234:
     Uncaught AssertionError: null == 'https://localhost.localhost.lan:8888/api/v1/map/23f0a323b3b5207f277c68a763403945:0/layer0/{z}/{x}/{y}.mvt?api_key=1234'
      at testClient.getLayergroup (test/acceptance/layergroup-metadata.js:38:24)
      at test/support/test-client.js:907:20
      at Server.<anonymous> (test/support/assert.js:120:24)
      at emitCloseNT (net.js:1555:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
[...]
```

But I also noticed its behavior depends on the config of the `renderer.mvt.usePostGIS` and it could even depend on the postgis version.

So, I'm wondering if the problem is the test itself, the postgis implementation or both. Is the metadata required to be exactly the same for mvt's rendered by mapnik and by postgis?

cc/ @Algunenano and @oleurud for awareness, and @dgaubert for brown dispatching (maybe RT?).

**Comment by rafatower** [comment]
https://github.com/CartoDB/Windshaft-cartodb/blob/master/test/acceptance/layergroup-metadata.js

**Comment by dgaubert** [comment]
> So, I'm wondering if the problem is the test itself, the postgis implementation or both. Is the metadata required to be exactly the same for mvt's rendered by mapnik and by postgis?

Yes, the metadata should be the same.

**Comment by dgaubert** [comment]
In a fresh installation in my environment, I get all green, both running `yarn test` and `yarn run docker-test` which they have also both Postgres/PostGIS's configurations `9.5/2.3` and `10/2.4`.

What configuration do you have?. Could you paste here the metadata content for that test? Because it's not failing the instantiation and the response has `body.metadata.layers[0].tilejson` at least.

**Comment by rafatower** [comment]
Unfortunately I deleted and got re-created my `config/environments/test.js`. I tried different things and I cannot reproduce it anymore. So I guess we can close this ticket. Sorry about the noise.
